### ISSUE TITLE
SIM cannot backup remote databases

### ISSUE THREAD

**Issue by mklimmasch** [Sitecore/Sitecore-Instance-Manager#103]
**Importance:**  
- **Normal** (I have a workaround, but it would be nice to fix it)  

**Description:**  
Apparently SIM cannot correctly backup/export remote databases. It looks like the backup path is created on the machine where SIM is running (machine A), then the BACKUP DATABASE command tries to write to the local filesystem (machine B) of the SQL Server instance.

**I am not sure whether this scenario is supported.**

**Scenario:**
1. Machine A contains the content management instance & SIM
2. Machine B contains the content delivery instance & the SQL Server database
3. Performing a backup/export via SIM on machine A leads to below Exception
4. Performing a backup/export via SIM on machine B works but is naturally missing the master database

...
  18 15:13:26,260 INFO  SQL query is executed: 
            BACKUP DATABASE [Sitecore_core]
            TO DISK = 'C:\57a9a641-fd07-4a9f-9088-a6e0ff86fd72\Databases\core.bak'          

  18 15:13:26,271 INFO  Processor of type 'SIM.Pipelines.Export.ExportDatabases' failed. Cannot open backup device 'C:\57a9a641-fd07-4a9f-9088-a6e0ff86fd72\Databases\core.bak'. Operating system error 3(The system cannot find the path specified.).
BACKUP DATABASE is terminating abnormally.
...

**Comment by AlenPelin** [comment]
It is a limitation of SQL Server, SIM just executes SQL command that is given to SQL. So the only thing we can do is to skip making backup of those databases.

N.B. SIM doesn't support remote SQL Server.

**Comment by mklimmasch** [comment]
Thank you for your reply! I suspected that might be the case but could not find an explicit statement.

Should I close the issue or leave it open?

**Comment by AlenPelin** [comment]
Does it throw an error that prevents the backup to complete for local databases? @mklimmasch

**Comment by mklimmasch** [comment]
It indeed throws an Exception and I guess the only way of preventing disruption of the backup is excluding the database (I only have remote DBs so I cannot test the "mixed" scenario).

**Comment by AlenPelin** [comment]
Okay, lets keep it as a bug until verified that local backups work well.

**Comment by DmitryKolinchuk** [comment]
Closed since the functionality is deprecated.
