### ISSUE TITLE
Download broken and chocolatey package outdated

### ISSUE THREAD

**Issue by WizX20** [Sitecore/Sitecore-Instance-Manager#106]
The download link http://dl.sitecore.net/updater/sim is broken.
https://chocolatey.org/packages/sim is an old version as far as I can see. Please update, or remove it.

**Comment by AlenPelin** [comment]
The only source of official distribution of SIM is ClickOnce at http://dl.sitecore.net/updater/sim, so chocolatey package is not an official one and we do not recommend to use it. As for the main download link, it works fine for me - could you @WizX20 elaborate what do you mean by broken?

P.S. SIM is an open-source application, you can download the source code and compile it.

**Comment by WizX20** [comment]
The ClickOnce URL is giving me a timeout: Location Amsterdam the Netherlands.

**Comment by AlenPelin** [comment]
I can suggest to ensure you don't have Fiddler sniffing is turned on.
