### ISSUE TITLE
Installing WFFM Module Freezes

### ISSUE THREAD

**Issue by WizX20** [Sitecore/Sitecore-Instance-Manager#108]
**Importance:**
Normal (I have a workaround, but it would be nice to fix it)  

**Description:**
Sitecore 8.2 WFFM module won't install correctly using SIM.

**Scenario:**
1. Download the zip for WFFM for Sitecore 8.2 and extract the contents
2. Run SIM
2. Create a new Site using Sitecore 8.2
3. Select 'Web Forms for Marketers 8.2 rev. 160801.zip'
4. SIM will never end installing the module, it will hang on post-install

**Comment by donaldallen** [comment]
I'm having the same issue as well. Not sure if it's related to SIM, but I also cannot install Web Forms for Marketers 8.2 rev. 160801 in the Sitecore admin either.

**Comment by AlenPelin** [comment]
Thanks @WizX20 for the issue report. 

N.B. The issue cause in fact that WFFM unlike normal modules exposes post-install actions try to interact with user which is not possible in SIM. It means we need to work around that and make sure everything is done excepting user interaction.

**Workaround** is simple - just abort installation, web forms typically are completely installed at this point.

**Comment by AlenPelin** [comment]
CC: @donaldallen

**Comment by DmitryKolinchuk** [comment]
Closed since Web Forms For Marketers was deprecated with the release of Sitecore XP 9.1:
[https://dev.sitecore.net/Downloads/Web_Forms_For_Marketers.aspx](https://dev.sitecore.net/Downloads/Web_Forms_For_Marketers.aspx)
