### ISSUE TITLE
Cosmetic : Typo with information window

### ISSUE THREAD

**Issue by michaellwest** [Sitecore/Sitecore-Instance-Manager#109]
The following statement is oddly phrased.

![image](https://cloud.githubusercontent.com/assets/933163/19335481/560b8c20-90c9-11e6-8f64-a240b4877e7a.png)

**Comment by AlenPelin** [comment]
**Proposed text:**
Website with same name already exists. Would you like to delete it?

**Comment by michaellwest** [comment]
A website with the name "INSERT NAME" already exists. Would you like to remove it?
