### ISSUE TITLE
Fail to create app pool for the instance when import

### ISSUE THREAD

**Issue by DanZhangSitecore** [Sitecore/Sitecore-Instance-Manager#111]
Importance:

**Normal** (I have a workaround, but it would like to know the reason causing it)

Description:
I can not replicate this issue on my side using the same version of SIM(1.4.0.383) and perform the same step, but more than one trainer has report the issue when they import a site, the app pool is not created by SIM so they need to manual create it. 

I had looked at the log they provided and think this might be related 

  26 10:37:54,912 INFO  Processor of type 'SIM.Pipelines.Import.ImportInitialization' failed. Ugyldigt navn på programgruppe

System.Runtime.InteropServices.COMException (0x8007000D): Ugyldigt navn på programgruppe

   ved Microsoft.Web.Administration.Interop.IAppHostProperty.set_Value(Object value)
   ved Microsoft.Web.Administration.ConfigurationElementCollectionBase`1.FindElementWithCollectionKey(String elementName, String collectionKey, Object value)
   ved Microsoft.Web.Administration.ApplicationPoolCollection.get_Item(String name)
   ved SIM.Pipelines.SetupWebsiteHelper.ChooseAppPoolName(String name, ApplicationPoolCollection applicationPools)
   ved SIM.Pipelines.Import.ImportInitialization.GetSettingsFromIISFiles(ImportArgs args)
   ved SIM.Pipelines.Import.ImportInitialization.Process(ImportArgs args)
   ved SIM.Pipelines.Import.ImportProcessor.Process(ProcessorArgs args)
   ved SIM.Pipelines.Processors.Processor.Execute(ProcessorArgs args)

But I have no idea what's causing it. Do you have any idea?

Screencast: http://screencast.com/t/BNctQOfRmPS 
Log files:
[2016-10-19_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/541737/2016-10-19_DEBUG.txt)
[2016-10-19.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/541738/2016-10-19.txt)

**Comment by AlenPelin** [comment]
This might happen when the website was exported from one Windows version and imported to another, it is related to IIS importing function.

**Comment by DanZhangSitecore** [comment]
Oh I see!! Thanks! Is there a way to work around this apart from ask the person to manually create the app pool after import?

**Comment by AlenPelin** [comment]
I believe it is the only way. Entire export/import functionality needs complete rewrite so it should be used with caution.

**Comment by DmitryKolinchuk** [comment]
Closed since the functionality is deprecated.
