### ISSUE TITLE
Import does not create a new mongo db connection string

### ISSUE THREAD

**Issue by Eldblom-zz** [Sitecore/Sitecore-Instance-Manager#114]
**Important**!

When importing an instance, the mongo db connection strings are the same as the original - even when the id for the imported site is different.

### To reproduce:
1. Install a new instance TEST
2. Export the instance
3. Import the exported instance as TEST2

**The instance TEST and TEST2 points to the same mongodb**

### Expected result:
 TEST and TEST2 points to different mongodb databases

Original:
![image](https://cloud.githubusercontent.com/assets/11038361/20367858/731d487e-aca5-11e6-8656-c218ffbaa436.png)

Imported:
![image](https://cloud.githubusercontent.com/assets/11038361/20367862/78f824f8-aca5-11e6-899d-2a8249feb52f.png)

**Comment by AlenPelin** [comment]
Valid. We should fix this during import/export rework project.

**Comment by jflheureux** [comment]
I started working on this issue yesterday because I need it fixed for one of my projects. Is anybody else started working on this?

**Comment by AlenPelin** [comment]
Needs QA session to ensure the issue is fixed.

**Comment by SaintSkeeta** [comment]
On this.... the SQL database names seem to also stay (close to) the same.
I believe it will try to keep them as the original, unless you already have the original dbs in your SQL instance, in which case it creates them as MyDBOriginalName_0, _1, _2 etc. (See Thomas' screenshots saying _2 for the SQL DBs).
It would be nice to have them follow the convention that a fresh instance follows.... being the name of the Website, and following the pattern defined in Core/SqlServer/DatabaseNamePattern.

i.e currently you get this
Original Website - MyOriginalSite - DB name is MyOriginalSite_master
Imported site - SomeNewSite - DB name is MyOriginalSite_master_0

should be

Original Website - MyOriginalSite - DB name is MyOriginalSite_master
Imported site - SomeNewSite - DB name is SomeNewSite_master

**Comment by DmitryKolinchuk** [comment]
Closed since the functionality is deprecated.
