### ISSUE TITLE
You cannot unselect the modules or packages that were selected on the previous forms\dialogs.

### ISSUE THREAD

**Issue by ArtemNizelnyk** [Sitecore/Sitecore-Instance-Manager#117]
**FYI** (I only wanted to let you know)

**Description:**
You cannot unselect the modules or packages that were selected on the previous forms\dialogs.

**Scenario:**
1. Click "Install Instance" button;
2. Next;
3. Next;
4. Select any module to be installed(e.g. EXM)
5. Next;
6. Back;
7. Unselect the modules from the 4th step;
8. Next;
9. Next;
10. Next;

Actual result: The module from the 4th step is displayed as the one that will be installed;
Expected result: There are no any additional modules to be installed.

**Comment by DmitryKolinchuk** [comment]
Closed since the functionality related to installation of Sitecore 8 and earlier versions is outdated.
