### ISSUE TITLE
Backup solr cores

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#118]
The idea is to extend SIM backup/restore pipeline to support Solr cores the same way it works with Lucene.

**Comment by AlenPelin** [comment]
@dsolovay what do you think?

**Comment by dsolovay** [comment]
Should be feasible if we have file system access to Solr (e.g. it is running locally), which is required for the Solr install feature. Then we just need to stop the index, copy the instance directory, and then restart the index.

**Comment by AlenPelin** [comment]
We do have as SIM supports only local services.

**Comment by AlenPelin** [comment]
Well, it seems Solr do supports backups the same way as SQL:
https://cwiki.apache.org/confluence/display/solr/Making+and+Restoring+Backups

**Comment by DmitryKolinchuk** [comment]
Closed since the "backup/restore" functionality is deprecated (disabled) for Sitecore 9 and later instances.
