### ISSUE TITLE
Solr support package options

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#119]
We need to extend Solr support package options to ask if it is the first Sitecore instance in the solution, and if not then ask the name of main instance and do not create cores if they already exist.

**Comment by AlenPelin** [comment]
@dsolovay your opinion?

**Comment by dsolovay** [comment]
Sharing cores across multiple Sitecore instances seems like a bad idea to me.  Technically, this will lead to _uniqueid collisions. The _uniqueid is comprised of database, ID, language, and version (e.g. `sitecore://master/{110d559f-dea5-42ea-9c1c-8a5df7e70ef9}?lang=en&ver=1&ndx=sitecore_master_index`, so having multiple instances use the same index will cause values to be overwritten.  This will also lead to items from one instance displaying in the results for another instance.

The current implementation embeds the name of the instance in the core name `{instance}_index_name`, following the pattern used for SQL and MongoDB databases, and ensures isolation.

**Comment by AlenPelin** [comment]
> Sharing cores across multiple Sitecore instances seems like a bad idea to me.
0_o are you serious? Solr is designed to be used by more than single Sitecore instance e.g. CM1+CM2 or CM+CD

**Comment by dsolovay** [comment]
Okay, fair point. I was thinking of, for example, my sc82u1 and my sc81u3 instances, since I use SIM primarily for feature exploration, and not (yet) as a provisioning tool.  My point is that you should not have shared indexes if you do not have shared DBs (at least logically shared, e.g. via replication).

For a more production like scenario, I can see the need to create a CM2 that has the same configuration as CM1, but does not generate indexes.  This is a pretty different feature from the one I built, so it might make sense to have a different configuration preset do this.  The preset could prompt for the instance to pattern after, and then grab the core names from that instance.

**Comment by AlenPelin** [comment]
SIM was not initially designed to work with scaled solutions, but it partially supports it:
* when installing an instance (e.g. `sc82.cd`) you can choose other database prefix (e.g. `sc82`) and disable installing databasees
* there are configs for enabling CD mode for 8.1

> it might make sense to have a different configuration preset do this. The preset could prompt for the instance to pattern after, and then grab the core names from that instance.
I'd vote for same zip package and manifest, but extra question because we cannot make it pure configuration preset (we need that zip's files).

**Comment by dsolovay** [comment]
I'm not using a zip package for 8.2. Are you looking to have this support 8.0 and 8.1?

**Comment by AlenPelin** [comment]
Yes, for 8.0 and 8.1. 
For 8.2 separate config pkg can work.

**Comment by dsolovay** [comment]
You can assign this to me.

**Comment by dsolovay** [comment]
What mechanism should I use to prompt the user? Specify a prompt in the manifest? Or is there another mechanism I should use?

**Comment by dsolovay** [comment]
### Steps to implement

Some milestones I anticipate: 
- [ ] Prompt user (Is there a way to give a list of current sites, and a drop down mechanism, or should this be a simple text box entry?)
- [ ] Verify site
- [ ] Reprompt if invalid site
- [ ] If site selected, for each index, determine name of index for other site (do not assume SIM+Solr naming convention).
- [ ] Set config to new name, but do not create core.

### Assumptions/Questions:   

* If an index is specified in configuration, but is not present in the existing site, should SIM:
   * Create it
   * Throw exception
   * Ignore it
 * Should SIM check if existing site is same release as new install? If different, should it indicate an error?

**Comment by AlenPelin** [comment]
@dsolovay I used to use prompt in cases like this. Check WindowHelper for necessary method.

**Comment by AlenPelin** [comment]
In my opinion it is enough to be silly i.e. with no verification.

**Comment by DmitryKolinchuk** [comment]
Closed since the functionality related to installation of Sitecore 8 and earlier versions is outdated.
