### ISSUE TITLE
Unable to download Sitecore package

### ISSUE THREAD

**Issue by gurtistheword** [Sitecore/Sitecore-Instance-Manager#121]
**Importance:**
Critical

The issue is that i cannot download any instance of Sitecore, due to a internal server error. The specific error is included in this issue.

**Scenario:**
1. Clean install of SIM. To be able to instantiate a Sitecore project, i need the base package installed.
2. I download the latest Sitecore installer, and i am prompted to login with my dev sitecore account.
3. after succesfully logging on, it proceeds the downloads, and immediately fails and returns a 500 error.

**Attachments:**
[2016-12-09.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/643283/2016-12-09.txt)
[2016-12-09_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/643282/2016-12-09_DEBUG.txt)
![capture](https://cloud.githubusercontent.com/assets/24484323/21065903/02f7f88a-be63-11e6-8be0-05d8aebcaa73.PNG)
![capture2](https://cloud.githubusercontent.com/assets/24484323/21065904/02fae3ec-be63-11e6-8da6-a8befef49d15.PNG)

**Comment by AlenPelin** [comment]
Thanks @gurtistheword for your issue report. I tried to replicate the issue and failed to do that as the 8.1 Update-1 was successfully downloaded. It could be an intermittent issue, but if not please try to download the file using your browser directly from [dev.sitecore.net](https://dev.sitecore.net) website.

**Comment by gurtistheword** [comment]
Thank your @AlenPelin for your response.

It does not seem to be an intermittent issue. However, one detail that might be relevant is that i am currently not a certified Sitecore developer (yet). I am currently following the course that enables me to become one. Might this be the reason why i cannot download these other Sitecore instances? Because you need certain permissions to download items on dev.sitecore.net which i do not have.

Again, thank you for your response :-)

**Comment by AlenPelin** [comment]
SIM is just another interface for downloading files from sdn/dev site. If you cannot download the file from it, then it's not SIM issue.
