### ISSUE TITLE
Chocolatey package to install via Click Once

### ISSUE THREAD

**Issue by rroman81** [Sitecore/Sitecore-Instance-Manager#124]
**Importance:**
**Normal** (I have a workaround, but it would be nice to fix it)

**Description:**
I currently do not see any way to bootstrap the installation of the SIM in automated fashion on developer machines.  I saw there was a choco-sim package but i think it no longer works.

**Scenario:**
1. Using Chocolatey to install SIM in developer workstation provisioning scenarios.
2. Utilize SIM to bring down target SiteCore instances' install files and perform base install (I think this is covered as your 2.0 enhancement).

**Comment by AlenPelin** [comment]
The app is only distributed only as a click once application. For SIM 1.x we are not going to change this schema. If you want you can maintain own choco package for SIM, but keep in mind that there are two channels of delivery: stable and QA. You can install both of them, run, find the files using Task Manager and pack for choco.
