### ISSUE TITLE
Create custom installation package

### ISSUE THREAD

**Issue by sbouwmeester** [Sitecore/Sitecore-Instance-Manager#127]
Hi,

For our Sitecore implemenation we are using SIM for creating the blank Sitecore installation. Now I am wondering how I can create a custom Sitecore installation. Our solution has WFFM, EXM, Sitecore Experience Extractor and some other external modules installed. It would be nice if I can create a starting point for our custom installation instead of installation all modules after the clean Sitecore installation.

Is there any solution for it?

Greetings,
Sander

**Comment by AlenPelin** [comment]
@sbouwmeester there are two ways of achieving this:
* using export/import functionality
* using own-made standalone product

The second option more flexible, but somewhat harder to create:
* prepare the instance to be a template
* stop the IIS website and application pool
* detach databases, clean up temp folders (logs, diagnostics, temp, upload, App_Data)
* make sure that database files are in <root>/databases folder and files named as default
* clean up ConnectionStrings.config file by replacing connection string details with default ones
* rename <root> folder to "Sitecore 8.1 rev. 160302" (so it matches original Sitecore version)
* archive the "Sitecore 8.1 rev. 160302" folder using 7zip (so zip contains "Sitecore 8.1 rev. 160302")
* create manifest `<zip file name>.manifest.xml` in the same folder where zip is

```xml
<manifest version="1.4">
  <standalone>
    <shortName>myproj</shortName>     
  </standalone>
</manifest>
```
