### ISSUE TITLE
Instance and backups are deleted when re-installing (or restoring): Locked files

### ISSUE THREAD

**Issue by WizX20** [Sitecore/Sitecore-Instance-Manager#129]
**Importance:**
**Normal** (I have a workaround, but it would be nice to fix it)

**Description:**
When one or more files are locked, reinstalling (or restoring) an instance will fail and will have deleted the entire instance including all backups.

**Scenario:**
1. With your instance running, open de log-viewer window and open the current log 'log' file;
2. Go back to the main window, right click the instance and choose to re-install the instance;
3. Re-installing will fail, and your instance will have been removed (in some cases my backups are also gone).

**Potential fixes:**
- Make sure SIM closes all windows (warning) before executing the action;
- Check for file locks on the instance before executing any actions, for example: http://stackoverflow.com/questions/24992681/powershell-check-if-a-file-is-locked#24992975

**Comment by AlenPelin** [comment]
Thanks @WizX20 for the issue report. 

> in some cases my backups are also gone
Could you clarify what kind of backups you mean and where they were located?

**Comment by WizX20** [comment]
1. Create a new instance with the path: c:\websites\my.website.local
2. Right click the instance in the main screen and choose the option: backup
3. Follow the steps
4. A new backup will be created in the default folder: c:\websites\my.website.local\backups

**Comment by AlenPelin** [comment]
It is expected behavior. Reinstall literally means completely delete the instance and install new one with same name and location.

**Comment by WizX20** [comment]
Cool, but except it won't reinstall the instance. Please follow the steps provided to reproduce the issue.

**Comment by AlenPelin** [comment]
Reinstall scenario is confirmed as a bug. Same to deleting an instance.
