### ISSUE TITLE
Cleanup solution before exporting

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#13]
In order to reduce the size of the export package, we can optionally cleanup WorkflowHistory, Properties, EventQueue, History tables in all the databases before exporting solution. Ideally these cleanup tasks should not affect original solution so all the databases should be first restored as copies, cleaned up and then backed up again.

**Comment by DmitryKolinchuk** [comment]
Closed since the "Backup -> Export" functionality is deprecated (disabled) for Sitecore 9 and later instances.
