### ISSUE TITLE
Installation 1.4.0.383 - Unable to retrieve application files 

### ISSUE THREAD

**Issue by andrewwburns** [Sitecore/Sitecore-Instance-Manager#130]
**Importance:**
**Critical** (I need this issue to be fixed)

**Description:**
Trying to install SIM 1.4.0.383 from http://dl.sitecore.net/updater/sim/ the files for it seem to download, but I receive a message "Unable to retrieve application files". I don't seem to be able to get past this.

From the log file... 
```
ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://dl.sitecore.net/updater/sim/SIM.Tool.application resulted in exception. Following failure messages were detected:
		+ Exception occurred loading manifest from file Ionic.Zip.Reduced.dll: the manifest may not be valid or the file could not be opened. 
		+ File Ionic.Zip.Reduced.dll is not a valid Portable Executable (PE) file.
		+ File {0} is not a valid Portable Executable (PE) file.

OPERATION PROGRESS STATUS
	* [16/01/2017 11:36:42] : Activation of http://dl.sitecore.net/updater/sim/SIM.Tool.application has started.
	* [16/01/2017 11:36:42] : Processing of deployment manifest has successfully completed.
	* [16/01/2017 11:36:42] : Installation of the application has started.
	* [16/01/2017 11:36:42] : Processing of application manifest has successfully completed.
	* [16/01/2017 11:36:44] : Found compatible runtime version 4.0.30319.
	* [16/01/2017 11:36:44] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [16/01/2017 11:37:46] System.Deployment.Application.InvalidDeploymentException (ManifestLoad)
		- Exception occurred loading manifest from file Ionic.Zip.Reduced.dll: the manifest may not be valid or the file could not be opened. 
		- Source: System.Deployment
```

See attachment for full stack trace.

**Attachments:**
Please find attached the error log file produced:
[SIM Error.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/708226/SIM.Error.txt)

**Comment by AlenPelin** [comment]
@andrewwburns did you try QA version instead?

**Comment by AlenPelin** [comment]
I cannot reproduce the issue both with PROD and QA versions of the tool in clean 2008R2 VM installation.

**Comment by andrewwburns** [comment]
Right, I've just tried the QA version, and got the same result; I have attached the log file. 
[SIM Error 2.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/710575/SIM.Error.2.txt)

I also got some of my colleagues to try to install SIM; for one it worked correctly, and for the other he got the same result, that downloading Ionic.Zip.Reduced.dll did not succeed.

I'm using Win10, and have tried using both IE Edge and Chrome.

**Comment by AlenPelin** [comment]
It looks like you have some issues with network connection. 
```
--- Inner Exception ---
		System.IO.IOException
		- Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
```
Do you use a proxy server?

**Comment by AlenPelin** [comment]
[SIM QA 1.4.0.528.zip](https://github.com/Sitecore/Sitecore-Instance-Manager/files/710605/SIM.QA.1.4.0.528.zip)

If you cannot make it work, here is the latest QA build.

**Comment by andrewwburns** [comment]
Yes, I thought it likely to be a network issue, but no, we don't use a proxy server.

The QA file you linked to seems to be working just fine, though.

**Comment by andrewwburns** [comment]
(Oh, and thank you!)

**Comment by AlenPelin** [comment]
You're welcome!
