### ISSUE TITLE
Unable to install Sitecore PowerShell Extensions (SPE) module with SIM. 

### ISSUE THREAD

**Issue by Martin-Miles** [Sitecore/Sitecore-Instance-Manager#131]
**Importance:**   
Normal

**Description:**  
Unable to install Sitecore PowerShell Extensions (SPE) module with SIM. 
Sitecore 8.2 Update 1 (but reproduces on others as well)

SPE 4.3 (full) from this official URL: https://marketplace.sitecore.net/services/~/download/6E72E3CC0747491D8485BC81C737B0FE.ashx?data=Sitecore%20PowerShell%20Extensions-4.3%20for%20Sitecore%208&itemId=6aaea046-83af-4ef1-ab91-87f5f9c1aa57

**Scenario:**  
1.  Download module
2. Try to install it for existing Sitecore instance like you'd normally do that with other modules (like WFFM) - "Add module"
3. SIM replies "Selected file is not a Sitecore module package"

**Attachments:**  
[Logs.zip](https://github.com/Sitecore/Sitecore-Instance-Manager/files/730170/Logs.zip)

**Comment by AlenPelin** [comment]
It is not an official Sitecore module, so must be installed by next step as Custom Package.

**Comment by AlenPelin** [comment]
Created wish #132

**Comment by zkniebel** [comment]
I actually experienced this same issue with SXA, which I thought would have been considered an official Sitecore module. Is this not the case? 

To that end - if it should be considered an official Sitecore module - note that SPE is required for SXA to run. I'm not sure if that will have an impact on implementation, but just something to bear in mind.

**Comment by AlenPelin** [comment]
@zkniebel SXA is not supported at the moment as it screwed up versioning policy (there are two different packages with the same version and revision).
