### ISSUE TITLE
Why Preheat is always enabled for the "Login as admin" button?

### ISSUE THREAD

**Issue by Zvirja** [Sitecore/Sitecore-Instance-Manager#133]
I've noticed that even if Preheat is disabled, it's still active for the `Login as Admin` button. In the [source code](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/8b29f5f87cd0c731168e6b6433e62098be8112de/src/SIM.Tool.Base/AuthenticationHelper.cs#L20) I can see that you pass the `true` parameter, meaning `ignoreAdvancedSetting`. Is there any reason for that? If not - could I just fire a PR to disable that annoying behavior?

**Comment by AlenPelin** [comment]
This is by design as without preheating the token may expire before user can use it.

**Comment by Zvirja** [comment]
The default lifetime is 5 minutes. I believe it will never be an issue for my PC. For such things it's always better to have settings.
Don't you mind if I introduce an Advanced Setting to suppress preheat for this feature?

**Comment by AlenPelin** [comment]
Well, it makes sense.  I forgot about 5 minutes, so let's open this bug - feel free to fix and PR without a setting.
