### ISSUE TITLE
Failure in PostInstallActions

### ISSUE THREAD

**Issue by MohammadChamanpara** [Sitecore/Sitecore-Instance-Manager#136]
**Importance:**  
Normal (I have a workaround, but it would be nice to fix it)  

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version [1.4.0.532]
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Description:**  
The issue is a failure in performing post-installation steps when SIM is installing a package on the platform.

**Scenario:**  
1.  Install the platform (e.g: 8.0.1 ) as well as the package (EXM 3.1.1) together.
2. The package post installation step fails with the following info logged:

_INFO  Requesting URL http://sc80u4.local/sitecore/shell/sim-agent/PostInstallActions.aspx?fileName=Email+Experience+Manager+3.1.1+rev.+150811.zip
Processor of type 'SIM.Pipelines.Install.Modules.PerformPostStepActions' failed. PostInstallActions.aspx returned an error: System.Net.WebException: The remote server returned an error: (500) Internal Server Error._

  
**Fix Suggestion**
In my local environment, I was able to solve the issue via changing the _sitecore/shell/sim-agent/PostInstallActions.aspx_ file, line 55 
from 
`Log.Info(string.Format("Custom PostStepAction executing: " + infoMessage, this);`
to 
 `Log.Info("Custom PostStepAction executing: " + infoMessage, this);`

Thank you.

**Comment by AlenPelin** [comment]
1. Doesn't clicking retry help to resolve the issue? Are you sure that the code change helps?
2. Can it be reproduced without EXM?

**Comment by MohammadChamanpara** [comment]
1. Retry doesn't help. After changing the .aspx page code and pressing the retry it works.
2. Installing the platform works fine but when I try to install the platform and module together this failure happens.

**Comment by MohammadChamanpara** [comment]
Thanks for your prompt action.
