### ISSUE TITLE
Error when trying to download Sitecore Instance Manager SIM (1.4) 

### ISSUE THREAD

**Issue by bmccrae** [Sitecore/Sitecore-Instance-Manager#139]
Unable to download the Sitecore Instance Manager SIM (1.4) tool on 2/20/2017 11:45AM EST.  Is there a problem with the download?  I get "This page cant' be displayed" Error-->.  http://dl.sitecore.net/updater/sim

**Comment by AlenPelin** [comment]
Cannot reproduce any longer. 

N.B. The dl.sitecore.net does not have 99.99% uptime SLA, so temporary unavailability is possible.
