### ISSUE TITLE
I still cannot download the tool.  It's been 3 days now...

### ISSUE THREAD

**Issue by bmccrae** [Sitecore/Sitecore-Instance-Manager#140]
It's been 3 days now that I cannot download the SIM (1.4) tool.  So this is not temporary unavailability.  The link http://dl.sitecore.net/updater/sim continues to fail with "The page can't be displayed error".  Any ideas of how I can get the tool?

**Comment by AlenPelin** [comment]
@bmccrae I believe it can be something to do with your firewall or ISP, as everybody else can download the tool easily. Did you try to open it from your phone? Home computer?

If you need further assistance, please provide fiddler2 dump that contains failed request and output of tracert dl.sitecore.net

**Comment by bmccrae** [comment]
Hi Alen,

You are correct!  My firewall was blocking the download.  Thanks for all your support..

Brian
