### ISSUE TITLE
After creating Sitecore instance its giving error while browsing a site as - "Root element is missing". Any idea how to resolve this.

### ISSUE THREAD

**Issue by akalgaonkar** [Sitecore/Sitecore-Instance-Manager#142]
**Importance:**  
Critical (I need this issue to be fixed)  

**Description:**  
After creating Sitecore instance its giving error while browsing a site as - "Root element is missing". Any idea how to resolve this.

**Attachments:**  
Root element is missing.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Xml.XmlException: Root element is missing.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[XmlException: Root element is missing.]
   System.Xml.XmlTextReaderImpl.Throw(Exception e) +88
   System.Xml.XmlTextReaderImpl.ParseDocumentContent() +1383
   System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace) +160
   System.Xml.XmlDocument.Load(XmlReader reader) +135
   System.Xml.XmlDocument.Load(String filename) +147
   Sitecore.Xml.XmlUtil.LoadXmlFile(String filename) +144
   ..() +19
   ...ctor(String fileName) +428
   Sitecore.Nexus.Licensing.NexusLicenseApi.() +285
   Sitecore.Nexus.Licensing.NexusLicenseApi.GetModuleCount(String name) +133
   Sitecore.Nexus.Licensing.NexusLicenseApi.HasModule(String name) +125
   Sitecore.Xdb.Configuration.XdbSettings.get_HasValidLicense() +22
   Sitecore.Xdb.Configuration.XdbSettings.get_Enabled() +9
   Sitecore.Analytics.Pipelines.Initialize.ShowXdbInfo.Process(PipelineArgs args) +216
   (Object , Object[] ) +71
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +484
   Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) +22
   Sitecore.Nexus.Web.HttpModule.Application_Start() +259
   Sitecore.Nexus.Web.HttpModule.Init(HttpApplication app) +680
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +618
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +402
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +343

[HttpException (0x80004005): Root element is missing.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +579
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +112
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +716
```

**Comment by AlenPelin** [comment]
Looks like license file issue. Please raise a support ticket.
