### ISSUE TITLE
SIM does not detect "Network Service" permissions in wwwroot

### ISSUE THREAD

**Issue by rroman81** [Sitecore/Sitecore-Instance-Manager#143]
**Importance:**  
Critical (I need this issue to be fixed)  

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version 1.4.1
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Description:**  
On  Windows 7 workstataion, the initial wizard cannot be completed as tool cannot correctly detect that "Network Service" account does have Full Access permission for c:\inetpub\wwwroot folder.  Pressing Grant button does not fix the issue as it reports successfully completed but we cannot click next.

**Scenario:**  
1.  Install SIM
2.  Grant "Network Service" the Full Access permissions
3.  Attempt to go through SIM wizard

**Comment by AlenPelin** [comment]
This is known issue, check github wiki



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by AlenPelin** [comment]
This is a known issue:
https://github.com/Sitecore/Sitecore-Instance-Manager/wiki/KnownIssue-SqlServerDefaultAccount

**Comment by AlenPelin** [comment]
@rroman81 please confirm you have resolved that.

**Comment by rroman81** [comment]
@AlenPelin I followed the directions inside this [article](http://sitecoreblog.patrickperrone.com/2015/04/a-simple-error.html) and that was the resolution.
Do you think it's worth modifying the logic slightly to detect the fact that Network Service filesystem permission is intact but the app is failing to create a test db, and thus report that most likely the database user specified in the connection string does not have "dbcreator" role.  That would make it more friendly.

**Comment by AlenPelin** [comment]
@rroman81 thanks for pointing out to this problem. We will take this into account during development of SIM 2.0.

**Comment by AlenPelin** [comment]
I've updated error description 
https://github.com/Sitecore/Sitecore-Instance-Manager/commit/7d1694a00c0eb0d6dffe1859bc2e104c7d5b0099

and also pointed that here:
dl.sitecore.net/updater/sim
dl.sitecore.net/updater/qa/sim
