### ISSUE TITLE
[SIM QA] Install Instance dialog does not refresh instances folder content

### ISSUE THREAD

**Issue by sergeyshushlyapin** [Sitecore/Sitecore-Instance-Manager#144]
Scenario:
1. Open SIM, Install new instance dialog
2. Check the list of available Sitecore versions, let's say there is only 8.1.0 available:
![image](https://cloud.githubusercontent.com/assets/4719165/23950495/d6053a3c-0993-11e7-90f1-042b92529237.png)

If you need to install another version, let's say 8.1.3 (which is not in the list), copy it to the Instances Root folder. Unfortunately the version does not appear in the list _until_ SIM is restarted:
![image](https://cloud.githubusercontent.com/assets/4719165/23950637/4cc06214-0994-11e7-8c5f-22e7eca2a4f6.png)

It should not be necessary to restart the entire program. The list of available versions should be updated _at least_ when opening the Install Instance dialog.

**Comment by AlenPelin** [comment]
It is not required to restart SIM, it is enough to click Main Window -> Ribbon -> Home -> Refresh -> Refresh Installer.

**Comment by AlenPelin** [comment]
Legacy, this project was developed 5 years ago and needs to be completely rewritten. If you want, you can head this process ;) talk to me if interested.
