### ISSUE TITLE
SIM Install command does not assign SQL permissions correctly

### ISSUE THREAD

**Issue by rroman81** [Sitecore/Sitecore-Instance-Manager#145]
**Importance:**  
Normal (I have a workaround, but it would be nice to fix it)  

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version v1.4.0.539
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Description:**  
I am using a non sysadmin database account in the connection string, but it does have "dbcreator" and "public" role.
I am attempting to run through "Installing new Instance" option of 8.2 update 1 and it generates an error under "Modules: starting instance".

Workaround is to go to Sql Server Management Studio and manually map the sql server login to target database user via user mapping option.  After doing that, I can hit retry inside the SIM to complete the installation.

**Scenario:**  
1. Create the sql server account and just assign dbcreator and public (attempting to use minimal privilege pattern here)
2. Run SIM and configure the account in the connection string
3. Run "Installing new Instance" option and it does not succeed.

**Comment by AlenPelin** [comment]
Valid point, nobody tested SIM with non-sa user account. 
Why don't you just use SA user account with 12345 password which is standard for the industry?

**Comment by rroman81** [comment]
in the workstation developer environment, i can see that being ok although i do not like the fact that the sa account is then used to attach db and provision connection strings. I can just see developers comitting their SA creds to the tfs or something. I would rather think that having SA to manage the sql instance and then during install step, we would define the sql login/ad auth that is then provisioned as part of the installation step itself.  
Furthermore, if we do use SIM in dev/qa tier provisoning (i am thiking long term that lots of great stuff that sim is doing could be exposed via commandline/automation then it becomes a good scenario for sitecore provisioning in all tiers).  Goal is repeat ability across tiers including local dev.
Fow now, I'll close this and adjust my local developer team instructions accordingly.

**Comment by AlenPelin** [comment]
Thanks for clarification. SIM 1.x is only designed for dev workstations, it is not a replacement for CI/installer.
SIM 2.0 is being planned to support other scenarios.
