### ISSUE TITLE
Host names are generated in reverse order

### ISSUE THREAD

**Issue by michaellwest** [Sitecore/Sitecore-Instance-Manager#149]
When I run the setup for a new instance the host names appear in reverse order of the site name.

![image](https://cloud.githubusercontent.com/assets/933163/24591945/c70abdac-17d2-11e7-88f1-8fd0b8aa22d6.png)

**Comment by AlenPelin** [comment]
This is by design, it is controlled by advanced setting `App/Product/HostName/Reverse`
https://github.com/Sitecore/Sitecore-Instance-Manager/issues/78

**Comment by michaellwest** [comment]
Thank you @AlenPelin .

**Comment by AlenPelin** [comment]
The reason is that you can have several websites grouped in IIS and on file system:
Host | IIS and Folder
-- | --
example.edit | edit.example.local
example.www | www.example.local
