### ISSUE TITLE
Importing the packages created with the latest SIM build

### ISSUE THREAD

**Issue by yaroskrinitskiy** [Sitecore/Sitecore-Instance-Manager#150]
**Importance:**  
Normal (I have a workaround, but it would be nice to fix it)  

**Description:**  
Import feature doesn't work with the packages built using the current SIM release (1.5.0.2).

**Scenario:**  
1. Export a Sitecore instance (8.2 initial or 8.2 upd-1, I have not tested with other versions)
2. Import the package built in step 1. 
->the window with the error pops up:

> Wrong package for import. The package doesn't contain the Website\Web.config file.

**Attachments:**  
The log files doesn't contain anything related. However, I'm attaching them anyway..
[2017-04-04.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/896296/2017-04-04.txt)
[2017-04-04_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/896295/2017-04-04_DEBUG.txt)

The workaround is to manually pull out the web.config from the package and insert it back (selecting the replace option).

**Comment by AlenPelin** [comment]
@yaroskrinitskiy please check last version (1.5.0.82) and confirm if it is fixed.

**Comment by heardk** [comment]
@AlenPelin I was getting this error when importing using the latest production release. I tried the QA release (1.5.0.104) and it works now.
