### ISSUE TITLE
Import fails when export is created using 1.5.0.2 and QA build 1.5.0.9

### ISSUE THREAD

**Issue by adamconn** [Sitecore/Sitecore-Instance-Manager#151]
**Importance:**  
Critical (I need this issue to be fixed)  

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version 1.5.0.9
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Description:**  
Exports created with SIM 1.5.0.2 or 1.5.0.9 cannot be imported.

SIM 1.5.0.2 and 1.5.0.9 can import sites if the site was exported using SIM 1.4.

**Scenario:**  
1.  Install Sitecore 8.2 update 2 using SIM (use all default options except changing the host name to match the site name)
2.  Remove reporting.apikey from ConnectionStrings.config.
3.  Use SIM to export the site (use all default settings) to a file SIM-TEST.zip.
3.  Use SIM to delete the site.
4.  Use SIM to import the site using SIM-TEST.zip.
5.  Error occurs: "Wrong package for import. The package does not contain the Website/Web.config file."

NOTE: SIM-TEST.zip does contain a file "Website/Web.config".

**Attachments:**  
Please find attached latest log files from this folders:

[Sitecore Instance Manager.zip](https://github.com/Sitecore/Sitecore-Instance-Manager/files/900100/Sitecore.Instance.Manager.zip)
[Sitecore Instance Manager-QA.zip](https://github.com/Sitecore/Sitecore-Instance-Manager/files/900101/Sitecore.Instance.Manager-QA.zip)

**Comment by adamconn** [comment]
This is a duplicate of #150.

**Comment by AlenPelin** [comment]
Closed due to duplicate.
