### ISSUE TITLE
SIM Download fails on invalid certificate

### ISSUE THREAD

**Issue by rroman81** [Sitecore/Sitecore-Instance-Manager#152]
**Importance:**  
Critical (I need this issue to be fixed)  

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version v1.5
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Description:**  
I recently had to get a new developer workstation which is running Windows 7SP1. I had to re-install the SIM tool. When I attempt to download I get a Certificate warning saying that certificate created by "Communications Server" is not trusted.  I have attempted to add the certificate to both personal and computer personal and trusted root store, and I still cannot get past the error.  It appears that ClickOnce app is hosted requiring the client cert.  Has anyone seen this issue and know any workarounds?

**Error Log**

PLATFORM VERSION INFO
	Windows 			: 6.1.7601.65536 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1590.0 built by: NETFXREL2
	clr.dll 			: 4.6.1590.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1590.0 built by: NETFXREL2
	dfshim.dll 			: 4.0.41209.0 (Main.041209-0000)

SOURCES
	Deployment url			: http://dl.sitecore.net/updater/qa/sim/SIM.Tool.QA.application
						Server		: Microsoft-IIS/7.5
						X-Powered-By	: ASP.NET
	Deployment Provider url		: http://dl.sitecore.net/updater/qa/sim/SIM.Tool.QA.application
	Application url			: http://dl.sitecore.net/updater/qa/sim/Application%20Files/SIM.Tool.QA.1.5.0.15/SIM.Tool.QA.exe.manifest
						Server		: Microsoft-IIS/7.5
						X-Powered-By	: ASP.NET

IDENTITIES
	Deployment Identity		: SIM.Tool.QA.application, Version=1.5.0.15, Culture=neutral, PublicKeyToken=abafaebf7cc9a2b2, processorArchitecture=x86
	Application Identity		: SIM.Tool.QA.exe, Version=1.5.0.15, Culture=neutral, PublicKeyToken=abafaebf7cc9a2b2, processorArchitecture=x86, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://dl.sitecore.net/updater/qa/sim/SIM.Tool.QA.application resulted in exception. Following failure messages were detected:
		+ Downloading http://dl.sitecore.net/updater/qa/sim/Application Files/SIM.Tool.QA.1.5.0.15/Copyrights.zip did not succeed.
		+ The remote server returned an error: (403) Forbidden.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [4/6/2017 12:54:38 PM] : Activation of http://dl.sitecore.net/updater/qa/sim/SIM.Tool.QA.application has started.
	* [4/6/2017 12:54:39 PM] : Processing of deployment manifest has successfully completed.
	* [4/6/2017 12:54:39 PM] : Installation of the application has started.
	* [4/6/2017 12:54:39 PM] : Processing of application manifest has successfully completed.
	* [4/6/2017 12:54:44 PM] : Found compatible runtime version 4.0.30319.
	* [4/6/2017 12:54:44 PM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [4/6/2017 12:55:35 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading http://dl.sitecore.net/updater/qa/sim/Application Files/SIM.Tool.QA.1.5.0.15/Copyrights.zip did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The remote server returned an error: (403) Forbidden.
		- Source: System
		- Stack trace:
			at System.Net.HttpWebRequest.GetResponse()
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by AlenPelin** [comment]
Cannot reproduce. So it was either intermittent issue with our server (which happens from time to time) or something wrong with that new Win7 os. 

I can propose a workaround if the issue still actual - on your existing machine where SIM works well, find its exe file using TaskManager, zip all files and copy to machine with problem.

**Comment by rroman81** [comment]
This ended up an issue with proxy in the corporate network after all.
