### ISSUE TITLE
SIM does not make DB backup when connectionString section is encrypted

### ISSUE THREAD

**Issue by rolek** [Sitecore/Sitecore-Instance-Manager#153]
According to best practices, that even Sitecore publishes, the connection strings section should be encrypted.

If this is the case, the SIM does not make DB backups, but reports OK which is confusing.

**Comment by AlenPelin** [comment]
Thanks for reporting this, we will take this into account when developing new backup engine for SIM2.

SIM is not designed for production-like environment, only for development where encryption does not make any sense.

**Comment by rolek** [comment]
Thanks for taking this into consideration.

**Comment by DmitryKolinchuk** [comment]
Closed since the backup functionality is deprecated (removed) for Sitecore 9+ instances.
