### ISSUE TITLE
Cleanup files before restore

### ISSUE THREAD

**Issue by adamconn** [Sitecore/Sitecore-Instance-Manager#159]
Files that are added to IIS after a backup is created remain on the file system after a restore. This means files must be located and removed manually after the restore runs.

There should be an option to restore where any added files are removed.

To reproduce:
1.	Create a backup of a site using SIM.
2.	Add a new dll to the bin folder on the website.
3.	Make a change to web.config.
4.	Change an item in a Sitecore database.
5.	Restore the backup using SIM.
6.	Changes 3 and 4 are lost, but change 2 is not.

**Comment by DmitryKolinchuk** [comment]
Closed since the "backup/restore" functionality is deprecated.
