### ISSUE TITLE
Reporting API key connection string

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#161]
**Scenario:**
1. Install Sitecore 8.2 Update-3
2. Check `reporting.apikey` connection string in the `ConnectionStrings.config` file

**Actual Result:**
The connection string contains some fake SQL connection string

**Expected Result:**
The connection string contains 32 zeros

**Comment by DmitryKolinchuk** [comment]
Closed since the functionality related to installation of Sitecore 8 and earlier versions is outdated.
