### ISSUE TITLE
Not able to use Get Sitecore or Install Instance

### ISSUE THREAD

**Issue by mahesh-bhide** [Sitecore/Sitecore-Instance-Manager#164]
**Importance:**  
Critical (I need this issue to be fixed)  
OR  
Normal (I have a workaround, but it would be nice to fix it)  
OR  
FYI (I only wanted to let you know)

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version [1.5.0.76]
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Description:**  
The issue is... When I click on Get Sitecore and Next and Next, I get error "Metadata for Sitecore Commerce Connect is absent"

**Scenario:**  
1.  Clicking on Get Sitecore and Next and Next
2.  Clicking on Install Instance
3. 

**Attachments:**  
Please find attached latest log files from this folders:
![image](https://cloud.githubusercontent.com/assets/17295143/26122471/a15a3ce6-3a45-11e7-8aa8-de930767a1da.png)

```
%APPDATA%\..\Roaming\Sitecore\Sitecore Instance Management\logs 
%APPDATA%\..\Roaming\Sitecore\Sitecore Instance Manager-QA\logs 
[2017-05-16.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1005483/2017-05-16.txt)

```

**Comment by AlenPelin** [comment]
Thanks @mahesh-bhide for reporting! It should be already fixed -  please verify.

**Comment by AlenPelin** [comment]
Fixed.
