### ISSUE TITLE
SIM2: Remote-IIS Adaptor

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#165]
Implement an adaptor that can control remote IIS instance using [Microsoft IIS Administration API](https://github.com/Microsoft/IIS.Administration). The supported logic should be:
* get list of all IIS sites and application pools
* create application pool with given settings
* create site with given settings

**Comment by AlenPelin** [comment]
Prerequisites for remote server:

* Enable IIS in Server Manager
* Reboot
* Install [DotNetCore.1.0.1-WindowsHosting.exe](https://download.microsoft.com/download/5/5/7/557D02A5-C3D0-4EF6-A570-4F75CD0DA5BF/DotNetCore.1.0.1-WindowsHosting.exe)
* Install [IIS Administration 1.1.1](https://download.microsoft.com/download/A/A/7/AA751AE2-010E-404E-AF5E-67016A2415D3/1.1.1/IISAdministrationSetup.exe)
* Configure firewall to open 55539 port in (if it's Azure VM do it in Azure Portal)
* Get access token by opening **https://**servername:55539/security/tokens

**Comment by AndreyFilchenkov** [comment]
Will not be implemented
