### ISSUE TITLE
SIM2: Remote-File-System adaptor

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#166]
Implement an adaptor that can connect to remote server file system using [Microsoft IIS Administration - Files API](https://blogs.iis.net/adminapi/iis-administration-preview-1-0-38-introducing-the-files-api). The supported logic should be:
* folder exists
* get folder's subfolders and files 
* read file
* write file
* assign permissions (?)

Depends on #165

**Comment by AlenPelin** [comment]
```C#
interface IRemoteFileSystemAdaptor : IResourceAdaptor
{
  bool IsFileExists(string filePath);
  bool IsFolderExists(string folderPath);
  Stream OpenRead();
  Stream OpenWrite();
  void Delete();
}
```

**Comment by AlenPelin** [comment]
Depends on #165

**Comment by AndreyFilchenkov** [comment]
Will not be implemented
