### ISSUE TITLE
SIM2: Commands overview

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#168]
Implement command-line interface that supports following commands:
* **sim web-add** to register remote Windows Server with IIS
* **sim sql-add** to register local or remote, SQL Server
* **sim mongo-add** to register local or remote MongoDB
* **sim solr-add** to register local or remote Solr
* **sim manifest-new** to create a manifest file from template 
* **sim manifest-check** to validate a manifest 
* **sim lockfile-new** to create a lock file for a manifest using registered resources
* **sim lockfile-check** to validate a lock file using a manifest
* **sim deploy** to perform deployment using manifest and lockfile
* **sim destroy** to remove deployed instances using manifest and lockfile

**Comment by AndreyFilchenkov** [comment]
Will not be implemented
