### ISSUE TITLE
Update package installer agent code

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#171]
It appeared that Installation Wizard in Sitecore uses somewhat different code that ignores certain installation errors whereas SIM aspx agent fails with exception and stops installation on first error.

**Scenario:**
1. Install new Sitecore 8.2 Update-3
2. Install PowerShell Extensions 4.5 for 8.0 full
3. Install SXA 1.3 Update-1

**Actual Result:**
Installation fails with exception

**Expected Result:**
Installation finishes correctly

**Comment by AndreyFilchenkov** [comment]
Closed as outdated
