### ISSUE TITLE
SIM2: Command-Line Engine

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#172]
Implement a command-line engine that meets following requirements:
* One-word command name as first argument
* JSON object as command arguments as further arguments (as JSON may be treated as several 'words')
* JSON object as command output to console buffer with properties:
  - Success
  - Result
  - Error
  - ReturnCode

**Comment by AndreyFilchenkov** [comment]
Will not be implemented
