### ISSUE TITLE
Sitecore SDN passwords fail with special characters

### ISSUE THREAD

**Issue by arencambre** [Sitecore/Sitecore-Instance-Manager#177]
**Importance:**  
Normal

**Valid for QA**  
(It appears the relevant code is already in 1.4 as it's from 11 months ago?)

**Description:**  
If my SDN password has certain special characters, then I cannot download a Sitecore zip using SIM. My SDN password may contain special characters, possibly characters such as a ^ or a !. Yeah, maybe. Anyway, it appears that on line 34 of **Sitecore-Instance-Manager/src/SIM.Tool.Windows/UserControls/Download8/Login.xaml.cs**, the username and password are thrown into a string with no escaping. Special characters that may be valid to an SDN account could interfere with interpretation of a string.

**Scenario:**  
1.  Have a SDN password with special characters that might mess with a string, such as a ! or a ^.
2. Through SIM, try to download a Sitecore package. You cannot log in via SIM.
3. Be sad and download the ZIP from dev.sitecore.net directly.

**Log**
This is the log entry:
```
  **  22 13:36:41,229 INFO  Long running task "Download Sitecore 8.x Wizard" failed with exception
System.InvalidOperationException: The username or password or both are incorrect, or an unexpected error happen
   at SIM.Tool.Windows.UserControls.Download8.Login.GetMarketplaceCookie(String username, String password)
   at SIM.Tool.Windows.UserControls.Download8.Login.<>c__DisplayClass4_0.<SIM.Tool.Base.Wizards.IFlowControl.OnMovingNext>b__0()
   at SIM.Tool.Base.WindowHelper.<>c__DisplayClass3_2.<LongRunningTask>b__0()
```

**Comment by DmitryKolinchuk** [comment]
Downloads from[ https://dev.sitecore.net]( https://dev.sitecore.net) are now publicly available, so the existing login functionality should be removed.
