### ISSUE TITLE
[SIMCMD] Add distribution package path option to install command

### ISSUE THREAD

**Issue by sergeyshushlyapin** [Sitecore/Sitecore-Instance-Manager#181]
Now, in order to install a new instance, I can use the following command:

```
sim install -n myinstance
```

In installs _some_ instance. Just wondering, how can I specify the source I want to be installed? I'd like it to be smth like the following:

```
sim install -n myinstance -s "C:\SIM_Repo\Sitecore 8.2 rev. 170429.zip"
```

I noticed there are `-p`, `-v` and `-r` parameters to specify the 'product', version and revision, but there is no parameter that could set the repository path:

```
C:\tools\SIM\Apps\SIMCMD>sim install -n myinstance -p 'Sitecore CMS' -v '8.2' -r '170407'
{
  "Success": false,
  "Message": "product is not found",
  "Elapsed": "00:00:00.0651080"
}
```

**Comment by AlenPelin** [comment]
Current simcmd depends on the concept of profile that stores certain values not to be repeated in each command call which came from GUI world where this was very actual. I agree that in command-line world the profile must be optional defaults and it should be possible to override these defaults. 

Implementation of this idea is not complicated and I will try to fix this tomorrow unless receive a PR today.

**Comment by sergeyshushlyapin** [comment]
This parameter works fine to me, thanks a lot!

But I simply forgot about all the other parameters required to get rig of the SIM profile configuration. For instance, `-l` for License file, `-s` for SQL Server connection and smth. like `-irf` for Instance Root Folder (not sure about the last param name).

Should I come up with another PR  for that? Thanks!

**Comment by AlenPelin** [comment]
Yes, having a PR with these would be great. I also suggest to split this install command into two pieces - one that uses profile and another which is not. I propose to name it as simple as installbare until the engine supports different sets of parameters.
