### ISSUE TITLE
SIM crashes on "Install Instance" under Win10 Enterprise

### ISSUE THREAD

**Issue by mgnoonan** [Sitecore/Sitecore-Instance-Manager#182]
**Importance:**  
Normal

**Description:**  
After installing and configuring SIM on Win10 using the same install instructions we use for Win7, clicking on Install Instance results in a hard crash "Sitecore Instance Manager has stopped working". This may be a permissions issue, since our corporate workstations are locked down more than usual and Win10 is new in our environment. I can't identify the problem enough to troubleshoot. I have attached the logs and the events from the Event Viewer.

**Scenario:**  
1. Launch SIM
2. Click on Install Instance
3. Result is a hard crash

**Attachments:**  
Please find attached latest log files from this folders:

[2017-06-21.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1092064/2017-06-21.txt)
[2017-06-21_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1092065/2017-06-21_DEBUG.txt)
[SIM - ERROR - 1026.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1092058/SIM.-.ERROR.-.1026.txt)
[SIM - ERROR - 1000.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1092057/SIM.-.ERROR.-.1000.txt)

**Comment by AlenPelin** [comment]
It looks like SIM cannot download Sitecore products metabase from `http://dl.sitecore.net/updater/info` - please make sure this operation is permitted. If it is not possible to make it permitted, you can copy `C:\ProgramData\Sitecore` folder from your working Win7 machine to target Win10 one.

**Comment by mgnoonan** [comment]
I was afraid it would be some kind of security setting, as I likely don't have permission to change that. Let me try your workaround and I will report back.

**Comment by mgnoonan** [comment]
While I agree that this is probably a configuration problem with my workstation, isn't there an opportunity here to add some error handling and logging for this specific situation @AlenPelin? Rather than just have the app crash with no warning or error message...

**Comment by AlenPelin** [comment]
Agree, it would be really good to get this fixed - PR is always appreciated.

**Comment by mgnoonan** [comment]
I'll see what I can do! :)
