### ISSUE TITLE
SIM does not remove IIS instance, root folder and hosts file record

### ISSUE THREAD

**Issue by sshushliapin** [Sitecore/Sitecore-Instance-Manager#184]
I've got a system with shut down mongo service. I can successfuly install an instance and use those features that do not requre mongo connection, e.g. Content Editor.

But, when I try to remove the instance, the "Deleting databases" step fails (because of the missing mongo connection) and few important steps ("Deleting root folder", "Deleting website" and "Updating the hosts file") are just ignored:

![image](https://user-images.githubusercontent.com/4719165/27517483-cf615d8e-59cd-11e7-8590-1e13e1faf078.png)

This makes impossible to install a new instance with the _same name_ until the IIS registration is removed manually (which is quite annoying and redundant). The missing mongo connection should bot be a locker for the valid IIS clean up.

**Comment by AlenPelin** [comment]
Valid, but quite a rare case - MongoDB is required for most Sitecore products, SIM does not offer CMS-only installations.

**Comment by sergeyshushlyapin** [comment]
The worst thing here is that from SIM perspective an instance is "successfully" deleted. It disappears from the instances list, but the website folder, IIS App domain and site registration are left. This breaks further installations (if name is the same).

**Comment by DmitryKolinchuk** [comment]
Closed since the functionality related to installation/uninstallation of Sitecore 8 and earlier versions is outdated.
