### ISSUE TITLE
SIM running as a background process but does not show up

### ISSUE THREAD

**Issue by bevinsunth** [Sitecore/Sitecore-Instance-Manager#185]
**Importance:**  
Critical (I need this issue to be fixed)  

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version 1.4
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Description:**  
I could see the SIM process running as a background process in task manager, But nothing shows up in the desktop. No errors in the event viewer.

**Scenario:**  
1.  QA version
2.  Latest Stable version

**Attachments:**  
Please find attached latest log files from this folders:
```
[Logs.zip](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1110936/Logs.zip)
[Logs.zip](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1110934/Logs.zip)

```

**Comment by AlenPelin** [comment]
1. HighDPI? 
2. Can you see this? Did you try right click - maximize?
![image](https://user-images.githubusercontent.com/2854666/27672140-21893a1c-5cdc-11e7-94f6-f0a88ce82479.png)

**Comment by bevinsunth** [comment]
I could see the program in the taskbar or in Alt+Tab.

**Comment by AlenPelin** [comment]
Collect memory dump via taskmgr and attach to the ticket.

**Comment by bevinsunth** [comment]
File is too big to attach, sharing gdrive share url
https://drive.google.com/file/d/0BxodJdX8W2cKSG1MOWppRm1MWG8/view?usp=sharing

**Comment by AlenPelin** [comment]
Something is wrong with the instances - try to modify profile file `%appdata%\sitecore\sitecore instance manager-qa\profiles\profile.xml` by pointing `<InstancesFolder>` to some empty folder e.g. `<InstancesFolder>C:\inetpub\logs</InstancesFolder>`.

**Comment by bevinsunth** [comment]
Profiles folder is empty, Can you attach the file to the ticket?

**Comment by AlenPelin** [comment]
Try to delete this folder completely: 
`%appdata%\sitecore\sitecore instance manager-qa`

**Comment by AlenPelin** [comment]
And reboot computer

**Comment by bevinsunth** [comment]
Still the Profiles folder is empty, All other folders got created.

**Comment by AlenPelin** [comment]
Try to create one:

```
<?xml version="1.0" encoding="utf-8"?>
<Profile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ConnectionString>Data Source=.;User ID=sa;Password=12345</ConnectionString>
  <InstancesFolder>C:\inetpub\wwwroot</InstancesFolder>
  <License>C:\Sitecore\Keys\Sitecore Partner.xml</License>
  <LocalRepository>C:\Sitecore\Repository</LocalRepository>
</Profile>
```

**Comment by bevinsunth** [comment]
It works now, Thanks!

**Comment by AlenPelin** [comment]
Good. Did you have any Sitecore instances installed before installing SIM? Any of them use Configuration Roles?

**Comment by bevinsunth** [comment]
No, It was a fresh setup, I had no sitecore instances installed before that.

**Comment by reyrahadian** [comment]
had the same problem, manually creating the profile.xml seems to fixed it. Using latest QA version

**Comment by AlenPelin** [comment]
@reyrahadian could you please confirm 
* if you had any files in C:\inetpub\wwroot folder before running SIM?
* if you had any IIS sites before running SIM?

**Comment by reyrahadian** [comment]
yes to both. My machine installation is preconfigured (from an image) so it already comes with preconfigured IIS sites

**Comment by AlenPelin** [comment]
So I assume the cause was in these files - SIM tried to guess some settings for you using this data.

**Comment by reyrahadian** [comment]
got it, thanks for the explanation. Did it just fails silently in the background then? would be nice if some warnings were shown

**Comment by AlenPelin** [comment]
I don't remember, good question to research.
