### ISSUE TITLE
Retry SOLR-based installation fails

### ISSUE THREAD

**Issue by sshushliapin** [Sitecore/Sitecore-Instance-Manager#188]
[Sitecore 8.2.4, Solr 6.6, SIM 1.5.0]

If for whatever reason installation of a SOLR-based instance failed (e.g. like [this one](https://sitecore.stackexchange.com/questions/6717/installing-a-solr-based-instance-via-sim-fails-with-401-unauthorized-error)), it's impossible to _Retry_ it since it will fail with new error trying to locate original (and currently missing) SOLR config files:

![image](https://user-images.githubusercontent.com/4719165/28418625-0788c616-6d65-11e7-88f8-dd367d242364.png)

**Comment by AlenPelin** [comment]
Thanks for reporting the issue. Indeed, the processor doesn't seem to support retrying.

**Comment by sergeyshushlyapin** [comment]
Is it OK to ignore the missing files so that the processor does not fail?

**Comment by AlenPelin** [comment]
@sergeyshushlyapin yes, that sounds well: no files -> good to go!

**Comment by DmitryKolinchuk** [comment]
Closed since the functionality related to installation of Sitecore 8 and earlier versions is outdated.
