### ISSUE TITLE
Installing 8.2 u4 with CD configuration role fails

### ISSUE THREAD

**Issue by ivansharamok** [Sitecore/Sitecore-Instance-Manager#191]
**Importance:**  
Critical (the functionality can't be used as advertised)  

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version 1.5.0.118
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Description:**  
When attempting to install Sitecore 8.2 u4 with ContentDelivery configuration role, the installation fails with error at the role configuration step. See attached image.
![sim-configrolesinstallerror](https://user-images.githubusercontent.com/2750708/29230254-0003b408-7e97-11e7-8aae-0e8dd5e0c509.PNG)

**Scenario:**  
1.  Start installation of Sitecore 8.2 u4.
2. Select "Install Sitecore Configuration Roles 1.3" checkbox
3. Select ContentDelivery (CD) option and try to install Sitecore instance.

**Attachments:**  
Please find attached latest log files from this folders:
```
%APPDATA%\..\Roaming\Sitecore\Sitecore Instance Management\logs 
%APPDATA%\..\Roaming\Sitecore\Sitecore Instance Manager-QA\logs 
```
[sim-logs.zip](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1218970/sim-logs.zip)

**Comment by ivansharamok** [comment]
The issue seems to be this line in `InstallRolesCommandHelper.InstallIncludeFiles` method:
```

string address = string.Format("https://github.com/Sitecore/Sitecore-Configuration-Roles/archive/configuration/{0}.zip", version);
```
The URL seem to be non-existent.

**Comment by AlenPelin** [comment]
Update-4 is not supported so far.

**Comment by AlenPelin** [comment]
Fixed.
