### ISSUE TITLE
[SIMCMD] Install a SOLR-based instance

### ISSUE THREAD

**Issue by sergeyshushlyapin** [Sitecore/Sitecore-Instance-Manager#196]
When I install an instance using the app, I can choose ContentSearch-SOLR _Configuration Preset_:

![image](https://user-images.githubusercontent.com/4719165/29855685-4e684fdc-8d56-11e7-9390-2e4cb19f259e.png)

Is it possible to do the same via command line? I noticed there is `-p` (product) option in the [`InstallCommandFacade`](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/d7611d450b04f067205aff9cd046bcdba922ae53/src/SIM.Client/Commands/InstallCommandFacade.cs#L27). Is that what I'm looking for?

**Comment by AlenPelin** [comment]
All configuration presets are formally "modules" so just go ahead and install that module via command line.

**Comment by sergeyshushlyapin** [comment]
when I try to install a moduleI recieve "product is not found" error:

```
> SIM.exe install -n mysite -p "Configuration - Sitecore 8.2 - ContentSearch - Solr.zip"

Installing instance 'mysite'...
{
  "Success": false,
  "Message": "product is not found",
  "Elapsed": "00:00:00.9262930"
}
```

Am I mising something?

**Comment by AlenPelin** [comment]
Two things:
1. sim.exe installmodule
2. the package with manifest needs to be physically copied to your local repository, currently it is in the same folder where SIM.Tool.exe lives.

**Comment by sergeyshushlyapin** [comment]
Why do I need to copy the package with manifest to the local repo if the UI tool does not require that?
In case I use the `installmodule`, what the params should I use? I tried:
```
.\SIM.exe installmodule -n mysite -m "Configuration - Sitecore 8.2 - ContentSearch - Solr.zip"
.\SIM.exe installmodule -n mysite -m "C:\tools\SIMRepository\Configuration - Sitecore 8.2 - ContentSearch - Solr.zip"
```

**Comment by AlenPelin** [comment]
Because UI was designed to do that, and for SIMCMD it is a workaround for a feature nobody designed nor tested.

**Comment by AlenPelin** [comment]
I don't have time to research that now, if you can - please try to debug in VS.

**Comment by BIGANDYT** [comment]
Did anyone resolve this, im trying to install wffm using simcmd

**Comment by AlenPelin** [comment]
SIMCMD is obsolete now with SIF release. All work is stopped now.
