### ISSUE TITLE
Retry for installing Solr module does not work

### ISSUE THREAD

**Issue by SC-MasoudAhmadi** [Sitecore/Sitecore-Instance-Manager#200]
**Importance:**  

Normal (I have a workaround, but it would be nice to fix it)  

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version 1.5.0.2
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Description:**  
If installing Solr module fails, the retry will never be successful because it will look for the config files that it has changed in the previous attempt, and when it cannot find them, it will throw an error

**Scenario:**  
1.  Install a new instance and check the Solr option
2. When SIM asks for the Solr URL, go to your instance dir and Rename the Sitecore.ContentSearch.Solr.DefaultIndexConfiguration.config.exmaple 
to 
Sitecore.ContentSearch.Solr.DefaultIndexConfiguration.config
3. Now give it the correct Solr URL

**Attachments:**  
Please find attached latest log files from this folders:
```
[Logs.zip](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1301797/Logs.zip)

```

**Comment by sergeyshushlyapin** [comment]
Duplicates #188? ;)

**Comment by SC-MasoudAhmadi** [comment]
yup. Found it afterward :)
