### ISSUE TITLE
Install Sitecore DB on Remote DB server through SIM

### ISSUE THREAD

**Issue by nitin-a** [Sitecore/Sitecore-Instance-Manager#201]
Normal (I have a workaround, but it would be nice to fix it)  

**Description:**  
The SIM does not connect to the remote SQL Server from Sitecore web server even using the Sa account and opening all the ports. We can access the SQL server using the management studio on the web server machine

**Scenario:**  
1. SQL Server on Server B  
2.  Sitecore on Server A using SIM and connection string pointing to Server B
3.  The SIM does not install the instance

**Comment by AlenPelin** [comment]
Remote SQL is not supported.
