### ISSUE TITLE
Import after export corrupt

### ISSUE THREAD

**Issue by scwoho** [Sitecore/Sitecore-Instance-Manager#202]
Critical (I need this issue to be fixed)  

Version 1.5.0.133

**Description:**  
I´m not able to extract a Sitecore Instance to a package and reinstall it from this package.
It seems that the folder structure of the export funktion does not match with the Sitecore package structure.
If I change the folder structure by myself the install process do work a bit longer, but does not extract the full install package. So I got no workaround for the SIM export and install feature.

**Scenario:**
1. I downloaded Sitecore 8.2 Update 5 (rev. 170728) as zip. Installed it via SIM 1.5.0.133.
2. Verified that the Instance is running (licence ...)
3. Used SIM "Export" feature to get a copy of my installation with all default dialog settings.
I used the naming "Sitecore 8.2 rev. 170920.zip"
4. Placed the "Sitecore 8.2 rev. 170920.zip" in my SIM Repository
5. Installed the instance via SIM install by selecting the version from the drop down and followed the dialog without changes.
6. the Installation broke with Error "The archive isn´t a Sitecore installation package"
![image](https://user-images.githubusercontent.com/32124646/30633434-e780882e-9deb-11e7-85eb-2264e939d04d.png)

**Attachments:**  
[2017-09-20_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1317024/2017-09-20_DEBUG.txt)
[2017-09-20.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1317025/2017-09-20.txt)

 
```

**Comment by AlenPelin** [comment]
Exported Sitecore instance is not supposed to be installed, it must be imported.

Rejected.

**Comment by scwoho** [comment]
Ah, thx for the quick response. 
That works for me, greate.
Confusing naming to import a instance "Import Solution" ;-)
