### ISSUE TITLE
How to install Sitecore 9 ? 

### ISSUE THREAD

**Issue by a3code** [Sitecore/Sitecore-Instance-Manager#206]
Could you please tell me how to install sitecore 9 with SIM ?
I put all possible zip files to \Sitecore Instance Manager\Repository
but I see only version 8 as an option to install

**Comment by AlenPelin** [comment]
It's available in qa version
Http://dl.Sitecore.net/updater/sim



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by a3code** [comment]
@AlenPelin I installed QA version. the same issue. No sitecore 9  at list.
How it should be ?

**Comment by AlenPelin** [comment]
Make sure that you used right zip installation package from dev Sitecore net



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by a3code** [comment]
@AlenPelin what do you mean  right zip file ?
what is correct names ?
I put 2 files with names (like it was downloaded): 
Sitecore 9.0.0 rev. 171002.zip
and
SitecoreInstallFramework 1.0 rev. 171003.zip

**Comment by AlenPelin** [comment]
@a3code `Sitecore 9.0.0 rev. 171002.zip` looks valid. The `SitecoreInstallFramework 1.0 rev. 171003.zip` one is not needed for SIM. 

It should work. Try refreshing caches (`Main Window -> Ribbon -> Home -> Refresh -> Refresh All`) and press `Install` button. This is how it looks at my side (`SIM QA 1.5.0.163`):

![image](https://user-images.githubusercontent.com/2854666/31923079-7b9d38c0-b8c4-11e7-81a3-90180b701f84.png)

**Comment by AlenPelin** [comment]
![image](https://user-images.githubusercontent.com/2854666/31923105-a8018d4e-b8c4-11e7-99db-084b307a9ca3.png)

![image](https://user-images.githubusercontent.com/2854666/31923120-b841444c-b8c4-11e7-8b12-a47d7568661c.png)

**Comment by a3code** [comment]
thanks ... it started work after full reload
