### ISSUE TITLE
Sitecore Instance Manager - Connect remote SQL Server and NETWORK SERVICE

### ISSUE THREAD

**Issue by jpbteixeira** [Sitecore/Sitecore-Instance-Manager#207]
Hi,

I'm deploying a fresh new installation of Sitecore with Sitecore Instance Manager.
I'm accessing DB on another server and I'm running SQL Server instance with a service account. Everything works fine and Sitecore can make the connection to SQL server, but in the next Sitecore Instance Manager window with content related to "Network Service" I'm receiving the error in the attach file:
![capture1](https://user-images.githubusercontent.com/18559320/31885381-41c812be-b7e8-11e7-8d8a-d8299dc33940.PNG)

I have check that NETWORK SERVICE account have full access to folder \inetpub\wwwroot. Attach file:
![capture2](https://user-images.githubusercontent.com/18559320/31885489-95995d8a-b7e8-11e7-9b25-4e5bfc404a3f.PNG)

What can be the reason of this error?

**Comment by anelsen** [comment]
I believe you need to double check Services.msc that your SQL Server is running as the Netowrk Service user like below:
![image](https://user-images.githubusercontent.com/5983174/31913656-70bfd302-b80d-11e7-9e59-26291cb6af4f.png)

**Comment by AlenPelin** [comment]
@jpbteixeira please don't ignore questions in the new issue template, it saves time for all of us.

* Confirm the issue is reproducible on the latest QA version which was downloaded today from http://dl.sitecore.net/updater/qa/sim
* Provide the log files

**Comment by AlenPelin** [comment]
Remote SQL Server is not supported, it is only for local development.
