### ISSUE TITLE
Internal Server Error when installing Careers module

### ISSUE THREAD

**Issue by jnegron357** [Sitecore/Sitecore-Instance-Manager#214]
**Description:**  
While attempting to install The Adventure Company - Careers Microsite using the SIM, I get an Internal Server Error (500), IIS 7.5 Detailed Error - 500.21, 

**Scenario:**  
1.  Open SIM
2.  Right Click on ssd.tack.local
3.  Select Install Module
4.  Choose the Careers Microsite module
5.  Step through dialogs
6.  Begin installation
7.  Receive error in the "Starting Instance" action if installation process

**Issue is actual**  
I hereby confirm the issue is new:
* all [prerequisites](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#prerequisites) are met.
* it is not a [known issue](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#knwon-ssue)
* it was not discussed before (I used GitHub Issues search)

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version [1.5.0.2]
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Screenshots:**
Please find screenshots attached.

**Attachments:**  
Please find attached latest log files from this folders:
```
%APPDATA%\..\Roaming\Sitecore\Sitecore Instance Management\logs 
%APPDATA%\..\Roaming\Sitecore\Sitecore Instance Manager-QA\logs 
```
[2017-12-06.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1537065/2017-12-06.txt)
![image](https://user-images.githubusercontent.com/3504712/33688132-627e0e36-daa8-11e7-9913-d8fe884174d8.png)
![image](https://user-images.githubusercontent.com/3504712/33688163-72bb935e-daa8-11e7-9efe-eed7c323dd68.png)

**Comment by AlenPelin** [comment]
Thanks @jnegron357 for reporting the issue. There are couple of moments to clarify:

* I cannot see mentioned log files attached
* I am not aware of such a module, it does not seem to be made by Sitecore, does it? 
  - If so, did you try to install it via Sitecore Desktop UI instead? It looks like a module issue.
* Latest QA version is definitely not 1.5.0.2, so please try actual QA version

**Comment by pjlx911** [comment]
Yep, I'm getting the same error as well.

It's also occurring on importing any packages (including the "Visual Studio 2015 Website Project" zip file). 

I have included a log to append to this issue. I don't know really what's going on as in SQL Manager, it does have the necessary permissions.

[2018-02-09.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1711594/2018-02-09.txt)

**Comment by JSpell** [comment]
I am dealing with a similar problem, but my install finishes without error, only to give the following error when I try to open the browser via SIM upon finishing.  

<img width="433" alt="screenshot 2018-02-15 14 09 38" src="https://user-images.githubusercontent.com/6892117/36275811-e1909f34-1259-11e8-95f4-86ff174482aa.png">

**Comment by AlenPelin** [comment]
@JSpell I managed to reproduce your issue, but it is not related to this one, so I registered as #221 and already fixed it. Relaunch your SIM QA couple times to get upgraded to newest version.

@pjlx911 you have something broken in your Cannot get data folder of `scisshit.dev.local` instance:
```
System.InvalidOperationException: Failed to get dataFolder sc variable of D:\sitecore\scroot\scisshit.dev.local\Website ---> System.InvalidOperationException: Failed to get web config result of D:\sitecore\scroot\scisshit.dev.local\Website ---> System.InvalidOperationException: Failed to build configuration. Reason: An error occurred during applying the patch file: D:\sitecore\scroot\scisshit.dev.local\Website\App_Config\Include\Project\PagerConfiguration.config
```
And it seems the instance is broken:
```
   1 10:59:25,606 ERROR Starting the instance action failed with message: The remote server returned an error: (500) Internal Server Error. 
```

**Comment by csandrea88** [comment]
Hi,

I am having a similar problem, but after I successfully install the Adventure Company - Careers Microsite.zip package thru both Sitecore UI or SIM, I can no longer back up the instance in SIM. I am getting the following error. 

 Cannot get data folder of C:\inetpub\wwwroot\scdev.tac.local\Website
System.InvalidOperationException: Failed to get dataFolder sc variable of C:\inetpub\wwwroot\scdev.tac.local\Website ---> System.InvalidOperationException: Failed to get web config result of C:\inetpub\wwwroot\scdev.tac.local\Website ---> System.InvalidOperationException: Failed to build configuration. Reason: An error occurred during applying the patch file: C:\inetpub\wwwroot\scdev.tac.local\Website\App_Config\Include\Project\PagerConfiguration.config

I feel that my permissions are correct, because before I installed this package, I am backing up/restoring in SIM just  fine.

My log files:
[2019-01-14.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/2757388/2019-01-14.txt)
[2019-01-14_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/2757389/2019-01-14_DEBUG.txt)

Thank you so much!
Andrea

**Comment by OliG19** [comment]
Hi 

Seem to be having a similar issue when install a module. My SIM is falling over at the modules: starting instance step and returns a 500 Internal Server Error.
Here is the following error: 

System.Net.WebException: The remote server returned an error: (500) Internal Server Error. 
Status: ProtocolError 
   at SIM.Instances.InstanceHelper.StartInstance(Instance instance, Nullable`1 timeout, String reason)
   at SIM.Pipelines.Install.Modules.StartInstance.Process(InstallArgs args)
   at SIM.Pipelines.Install.InstallProcessor.Process(ProcessorArgs args)
   at SIM.Pipelines.Processors.Processor.Execute(ProcessorArgs args)
   1 13:03:43,554 ERROR Modules: starting instance action failed with message: The remote server returned an error: (500) Internal Server Error. 
Status: ProtocolError 
   1 13:03:47,903 ERROR Modules: starting instance action failed with message: The remote server returned an error: (500) Internal Server Error. 
Status: ProtocolError 
[2019-08-29.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/3555458/2019-08-29.txt)
[2019-08-29_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/3555459/2019-08-29_DEBUG.txt)

**Comment by dharmnathdubal** [comment]
Hi,
While attempting to install The Adventure Company - Careers Microsite using the SIM, I get below error. can anyone know how to resolve this issue or exception?

The processor of type 'SIM.Pipelines.Install.Modules.StartInstance' failed. The remote server returned an error: (500) Internal Server Error. 
Status: ProtocolError 
Name cannot begin with the '&lt;' character, hexadecimal value 0x3C. Line 3, position 2.
System.Net.WebException: The remote server returned an error: (500) Internal Server Error. 
Status: ProtocolError 
Thanks
