### ISSUE TITLE
SIM - Install Habitat (demo) withs SIM 1.5.0.186

### ISSUE THREAD

**Issue by GreedPrimo** [Sitecore/Sitecore-Instance-Manager#219]
Hi 
I can't install my habitat demo since  sim migration (1.4 to 1.5)
When I want to install Habitat I have this :

![image](https://user-images.githubusercontent.com/14822906/35874522-fd1bd12c-0b6c-11e8-9fa2-fb7f5bc55aa1.png)

conf : 

![image](https://user-images.githubusercontent.com/14822906/35874589-3128f008-0b6d-11e8-956e-52f161c7760a.png)

after I click next to install button.
My zip demo : 

![image](https://user-images.githubusercontent.com/14822906/35874669-73f5b16e-0b6d-11e8-9d9e-2402330be714.png)

Have you a solution, or a trick?
Thanks :)

**Comment by AlenPelin** [comment]
This is a known issue. There is a solution:
* Open zip file
* Rename root folder in zip to have "Sitecore " prefix

**Comment by GreedPrimo** [comment]
Thanks for it :)
