### ISSUE TITLE
Backup fails with SC9

### ISSUE THREAD

**Issue by xc-tonycwang** [Sitecore/Sitecore-Instance-Manager#222]
**Description:**  
When attempting to back up a SC9 instance, the backup fails because it's unable to find databases associated with experience platform.

**Scenario:**  
1. Install SC9 with SIM
2. Backup instance from the above step.
3. Get Error

**Issue is actual**  
I hereby confirm the issue is new:
* all [prerequisites](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#prerequisites) are met.
* it is not a [known issue](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#knwon-ssue)
* it was not discussed before (I used GitHub Issues search)

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version [1.5.0.190]
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Screenshots:**
Please find screenshots attached.
![backup selection](https://user-images.githubusercontent.com/26232097/36547785-8e77dd98-17e6-11e8-8a3b-c2dc569418d7.png)
![backup error](https://user-images.githubusercontent.com/26232097/36547791-90af3aa2-17e6-11e8-88df-cdad77d29aeb.png)

**Attachments:**  
Please find attached latest log files from this folders:
```
%APPDATA%\..\Roaming\Sitecore\Sitecore Instance Manager-QA\logs 
```
[2018-02-22.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/1748499/2018-02-22.txt)

**Comment by xc-tonycwang** [comment]
This error appears to be an issue related to the XP databases that are not installed during CMS install.  Once I commented out the connection strings, the backup worked as expected.  Would it be possible for SIM to either ignore those connection strings, or commented out those entries during install?

**Comment by isaadansari** [comment]
I am getting the similar error 

`---------------------------
Sitecore Instance Manager
---------------------------
Backing up databases action failed with message: Cannot open backup device 'C:\inetpub\wwwroot\sxa.sc backups\2018-07-09 at 09-21-01\Databases\core.bak'. Operating system error 5(Access is denied.).

BACKUP DATABASE is terminating abnormally.

You can find details in the log file. Would you like to open it?
`

**Comment by AlenPelin** [comment]
@isaadansari that's permissions error, make sure that SQL Server has write access rights to `C:\inetpub\wwwroot\sxa.sc backups\2018-07-09 at 09-21-01\Databases` folder (try to create backup to that folder manually vis SSMS).

**Comment by DmitryKolinchuk** [comment]
Closed since the backup functionality is deprecated (removed) for Sitecore 9+ instances.
