### ISSUE TITLE
Unify installation buttons

### ISSUE THREAD

**Issue by RomanChernyk** [Sitecore/Sitecore-Instance-Manager#238]
We should have a single button that allows installing all Sitecore versions.

**Comment by RomanChernyk** [comment]
Implement similarly to Refresh Sites button with a dropdown the allows to select a necessary major version. By default Sitecore 9 should be selected.

**Comment by DmitryKolinchuk** [comment]
Implemented by the following PR:
[https://github.com/Sitecore/Sitecore-Instance-Manager/pull/265](https://github.com/Sitecore/Sitecore-Instance-Manager/pull/265)
