### ISSUE TITLE
Enable automatic installation of SIF if it is not installed

### ISSUE THREAD

**Issue by RomanChernyk** [Sitecore/Sitecore-Instance-Manager#241]

**Comment by RomanChernyk** [comment]
This should be an automatic step when installing new Sitecore 9 instance

**Comment by RomanChernyk** [comment]
Installing/Validating SIF should be reflected in installation UI somehow.

**Comment by IvanSheyenko** [comment]
done

**Comment by IvanSheyenko** [comment]
@AndreyFilchenkov please test

**Comment by AndreyFilchenkov** [comment]
Prerequisites: PC without SIF 1.2.1(required in 9.0.x)

**Scenario#1:**
1. Install SC902;
2. Check 'scripts only' checkbox;
3. Run 'Install SIF 1.2.1.ps1' script with admin privileges;

Actual Result: OK.
SIF 1.2.1 has been installed successfully.

**Scenario#2:**
1. Try to install SC902 using UI;

Actual Result: NOT OK.
SIF 1.2.1 has NOT been installed.

@IvanSheyenko could you check 2-nd scenario?
Tested on: 5c6bbcf7ea29eafdf8a359f4009b38b34dfbc6ee

**Comment by IvanSheyenko** [comment]
@AndreyFilchenkov works fine for me

**Comment by AndreyFilchenkov** [comment]
It works for me as well.
