### ISSUE TITLE
Enable validation for various installation prerequisites

### ISSUE THREAD

**Issue by RomanChernyk** [Sitecore/Sitecore-Instance-Manager#243]
Please fill the body

**Comment by AndreyFilchenkov** [comment]
**Add basic SC9 validation**
1) Add them to the list (e.g. 'Basic SC9 install validators') of the 'Validators.json' file;

2) Add the validation list to the 'GlobalParams_*' files of all supported topologies.

3) Implement the validators and add them to the 'Basic SC9 install validators' list:
- SqlServer (up and running; provide warning in case the SQL server contains the DBs with the $sqldbprefix);
- LicenseFile (file exists physically, etc.);
- DnsName (has already been implemented);
- Solr (instance is up running, the 'SolrRoot' folder exists, there are not cores/folders with the $sqldbprefix);
- DiskSpace (check a free HDD space on the target server; show a warning if there is a shortage of free space);
- IIS validation (presence sites/apppools with $sqldbprefix, site folders under wwwroot etc.)
