### ISSUE TITLE
Introduce support for multiple Solr instances

### ISSUE THREAD

**Issue by RomanChernyk** [Sitecore/Sitecore-Instance-Manager#244]
When installing new instance it should be possible to select existing or add new Solr configuration.

The selected/added configuration should be remembered and selected by default when installing the same major Sitecore version next time.

**Comment by RomanChernyk** [comment]
The UI should be something like the following:
1. Solr URL, Solr root and Solr service fields should be extracted into a separate window, that allows adding a new Solr configuration.
The windows should have **Configuration Name** field additionally in order to name the set.

2. There should be a single dropdown in the **Installing new instance** wizard that allows selecting desired Solr configuration.

3. There should be **"..."** button before the dropdown that allows adding new Solr configuration.

**Comment by RomanChernyk** [comment]
It should also be possible to edit existing configurations and extend them from Settings UI.

**Comment by IvanSheyenko** [comment]
Done.

**Comment by RomanChernyk** [comment]
- Move Solr table into a separate window from the Configuration box. It should be opened when clicking on "..." button
- When installing a new instance and adding additional Solr configuration, the Solr Root field should contain "..." button to open File Explorer.

CC @IvanSheyenko @AndreyFilchenkov

**Comment by RomanChernyk** [comment]
Let's also pre-fill the Solr Url field with the default url https://localhost:8983/solr when adding a new instance

**Comment by IvanSheyenko** [comment]
> * When installing a new instance and adding additional Solr configuration, the Solr Root field should contain "..." button to open File Explorer.
> 
Done

**Comment by RomanChernyk** [comment]
Align label and text box:
![image](https://user-images.githubusercontent.com/12621581/62053500-62ee6900-b220-11e9-8dd7-c7f063b6fdef.png)

**Comment by RomanChernyk** [comment]
Enable a user-friendly data validation. Right now I see the following error when trying to submit an empty form

![image](https://user-images.githubusercontent.com/12621581/62053877-2cfdb480-b221-11e9-94e7-b4cc0f9ee69b.png)

**Comment by RomanChernyk** [comment]
Validate Solr url. It must be of a specific format:
https://localhost:8983/solr

It must not contain a trailing space or any other signs.
We should validate this.

Otherwise, there are errors during installation when starting services which are quite hard to debug.

**Comment by RomanChernyk** [comment]
> Let's also pre-fill the Solr Url field with the default url https://localhost:8983/solr when adding a new instance

Done in Sitecore installation UI. Let's skip this for Advanced Settings window

**Comment by RomanChernyk** [comment]
>Align label and text box:
Done.

**Comment by RomanChernyk** [comment]
Open questions left:
Validation and friendly error messages in dialogs (Settings and "+" dialog when adding Solr during installation)

**Comment by IvanSheyenko** [comment]
Done

**Comment by IvanSheyenko** [comment]
Validate Solr url. It must be of a specific format:
https://localhost:8983/solr

**Comment by IvanSheyenko** [comment]
Done
