### ISSUE TITLE
Reconsider the UI of advanced installation settings

### ISSUE THREAD

**Issue by RomanChernyk** [Sitecore/Sitecore-Instance-Manager#246]
Reconsider tabs. Horizontal scroll of tabs does not look very user-friendly. Let's think about how we can change this.

![image](https://user-images.githubusercontent.com/12621581/58623199-1ba63380-82d6-11e9-9752-db0bc8606dba.png)

**Comment by IvanSheyenko** [comment]
![image](https://user-images.githubusercontent.com/13461196/76124137-0a5a2800-5fc8-11ea-87e7-642ed15cf1f6.png)
Not sure if this is better. @RomanChernyk please check

**Comment by RomanChernyk** [comment]
Looks good to me.
