### ISSUE TITLE
It should be possible to uninstall/reinstall the whole environment of Sitecore 9 installation

### ISSUE THREAD

**Issue by RomanChernyk** [Sitecore/Sitecore-Instance-Manager#248]
Sitecore 9.0 and 9.1. xm0, xm1, xp0 and xp1 topologies.

**Comment by IvanSheyenko** [comment]
9.1+ uninstall is functional.
To do:
- Need to investigate 9.0 uninstall 
- Review saved unInstall parameters and remove unnecessary ones.

**Comment by IvanSheyenko** [comment]
remove uninstall params for deleted instances
do not save uninstall params for json without uninstall tasks

**Comment by IvanSheyenko** [comment]
investigate the removal of uninstall params when reinstalling

**Comment by IvanSheyenko** [comment]
reinstall for 9.1+ is functional

**Comment by IvanSheyenko** [comment]
remove advanced parameters step from delete UI

**Comment by IvanSheyenko** [comment]
@RomanChernyk check text for re-install dialog

**Comment by RomanChernyk** [comment]
Align the checkbox with the field:
![image](https://user-images.githubusercontent.com/12621581/62368779-4a3ec580-b536-11e9-91f9-f03cf908f1f4.png)

**Comment by RomanChernyk** [comment]
@IvanSheyenko why do we need a Solr dropdown when uninstalling?

**Comment by RomanChernyk** [comment]
![image](https://user-images.githubusercontent.com/12621581/62369041-0c8e6c80-b537-11e9-9e97-4277429a9344.png)

**Comment by AndreyFilchenkov** [comment]
* ```uninstall 9.0.x``` feature was implemented via e813f51477714698f49d2b1a0cdca817f800706b
* feature has been merged to ```install9``` branch

**Comment by IvanSheyenko** [comment]
Fixed UI and typo
