### ISSUE TITLE
dds patch task does not work with default parameters

### ISSUE THREAD

**Issue by IvanSheyenko** [Sitecore/Sitecore-Instance-Manager#253]
dds patch task does not work with default parameters. Need to set correct values for sitename and dedicatedserverhostname

**Comment by RomanChernyk** [comment]
@IvanSheyenk, @RomanChernyk , @AndreyFilchenkov  to test

**Comment by AndreyFilchenkov** [comment]
The issue is not reproducible on the latest build.

Also fixed value of the 'DedicatedServerHostName' settings in *XP1.json files  [37af86d11f88be41ea0fa4432a71bfec69e3c0fd]
