### ISSUE TITLE
Do not re-use confirmation control in re-install 9 

### ISSUE THREAD

**Issue by IvanSheyenko** [Sitecore/Sitecore-Instance-Manager#257]
Do not re-use confirmation control in re-install 9

**Comment by RomanChernyk** [comment]
When implementing this keep in mind the following comments:
![image](https://user-images.githubusercontent.com/12621581/62547696-51cfd880-b86e-11e9-9023-0eed5a7de405.png)

**Comment by IvanSheyenko** [comment]
Done

**Comment by RomanChernyk** [comment]
@RomanChernyk and @AndreyFilchenkov to test

**Comment by AndreyFilchenkov** [comment]
**Actual Result:**
An instance name is being still displayed.
![image](https://user-images.githubusercontent.com/22079019/68090750-1b5f2500-fe80-11e9-9e35-8814e53d111b.png)

**Expected Result:**
Environment name should be displayed

@IvanSheyenko Can we fix this?

**Comment by AndreyFilchenkov** [comment]
The last reported issue was fixed in the scope of work on the #279 
I think that this issue could be considered as a completed one.
