### ISSUE TITLE
Align fields in Sitecore 9 installation window

### ISSUE THREAD

**Issue by RomanChernyk** [Sitecore/Sitecore-Instance-Manager#258]
Please align the field, button, and labels in highlighted areas:
![image](https://user-images.githubusercontent.com/12621581/61820950-c7937780-ae5e-11e9-929d-2b7660320620.png)

**Comment by IvanSheyenko** [comment]
adjusted. @RomanChernyk, please check

**Comment by RomanChernyk** [comment]
@IvanSheyenko looks good. thx. One last moment :)
![image](https://user-images.githubusercontent.com/12621581/62519176-be79b180-b833-11e9-9e81-ef24239ecd48.png)

**Comment by IvanSheyenko** [comment]
Fixed

**Comment by RomanChernyk** [comment]
Perfect. Thanks!
