### ISSUE TITLE
Investigate SIM performance

### ISSUE THREAD

**Issue by IvanSheyenko** [Sitecore/Sitecore-Instance-Manager#259]
Clicking a ribbon button to run any wizard takes long time.
```
//SIM.Tool.Windows 
private static RoutedEventHandler GetClickHandler(IMainWindowButton mainWindowButton)
    {
      var clickHandler = new RoutedEventHandler(delegate
      {
        try
        {
          if (mainWindowButton != null && mainWindowButton.IsEnabled(MainWindow.Instance, SelectedInstance))
          {
            mainWindowButton.OnClick(MainWindow.Instance, SelectedInstance);
            RefreshInstances();
          }
        }
        catch (Exception ex)
        {
          WindowHelper.HandleError("Failed to get click handler", true, ex);
        }
      });

      return clickHandler;
    }
```

This is a global button click handler and it invokes RefreshInstances() on any button click. RefreshInstances is a heavy operation. It seems that calling it on each button click is excessive. 
Need to investigate the impact of removing the call or alternative ways to improve performance.

**Comment by RomanChernyk** [comment]
@IvanSheyenko is this line present in the master branch as well? Maybe this is something added as part of something in develop?

**Comment by ViacheslavAfanasyev** [comment]
It doesn't invoke RefreshInstances()  anymore. It seems it has been fixed with my previous PRs.
@AndreyFilchenkov 
Also, it isn't reproducible.
Close
