### ISSUE TITLE
Create globalParams file for 9.2 XP1

### ISSUE THREAD

**Issue by IvanSheyenko** [Sitecore/Sitecore-Instance-Manager#262]
Can be created based on 9.1.1 XP1

**Comment by RomanChernyk** [comment]
Let's ensure we have params for all version and topologies:
9.0, 9.1, 9.2 + XM0, XM1, XP0, XP1

**Comment by IvanSheyenko** [comment]
Installation packages for XM0 are not available.

**Comment by RomanChernyk** [comment]
@RomanChernyk and @AndreyFilchenkov to test

**Comment by AndreyFilchenkov** [comment]
We have global params files for all topologies:
9.0, 9.1, 9.2 + XM1, XP0, XP1.
Verified in: 5c6bbcf7ea29eafdf8a359f4009b38b34dfbc6ee
