### ISSUE TITLE
Remove useless tasks from reinstall tasks list

### ISSUE THREAD

**Issue by AndreyFilchenkov** [Sitecore/Sitecore-Instance-Manager#272]
The following tasks are useless when an instance is being reinstalled.
We should remove them from reinstall tasks list:
* Install SIF
* Prerequisites

![image](https://user-images.githubusercontent.com/22079019/66216046-63e2c180-e6cd-11e9-8550-452a2cb254da.png)

**Comment by IvanSheyenko** [comment]
will be fixed in the scope of #277

**Comment by IvanSheyenko** [comment]
fixed
