### ISSUE TITLE
sitecore verion 9.1 002459 Update -1 Login security login sa error

### ISSUE THREAD

**Issue by nickgsoft** [Sitecore/Sitecore-Instance-Manager#273]
i installed sitecore verion 9.1 002459-update 1 using sim, and after installation is successful, while opening into browser, it gives this security error
"Cannot open database "sc911_security" requested by the login. The login failed.
Login failed for user 'sa'."

Any insight on is this can be resolved?

![image](https://user-images.githubusercontent.com/12518671/66255328-ef009d80-e747-11e9-8ad3-db4ddbf10353.png)

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!! READ THIS CAREFULLY !!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                     !!
!! 1. Do not remove any sections from this template    !!
!! 2. Do not create issue without SIM version AND logs !!
!! 3. Remove this disclaimer before posting issue      !!
!!                                                     !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Description:**  
The issue is...

**Scenario:**  
1.  
2. 
3. 

**Issue is actual**  
I hereby confirm the issue is new:
* all [prerequisites](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#prerequisites) are met.
* it is not a [known issue](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#knwon-ssue)
* it was not discussed before (I used GitHub Issues search)

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version [PUT HERE EXACT VERSION NUMBER]
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Screenshots:**
Please find screenshots attached.

**Attachments:**  
Please find attached latest log files from this folders:
```
%APPDATA%\..\Roaming\Sitecore\Sitecore Instance Management\logs 
%APPDATA%\..\Roaming\Sitecore\Sitecore Instance Manager-QA\logs 
```

**Comment by RomanChernyk** [comment]
@nickgsoft Hi Nick! The released and QA versions of SIM do not support installing 9.1 at the moment, however, the work is ongoing.

You can check the following branch where we are developing this part:
https://github.com/Sitecore/Sitecore-Instance-Manager/tree/feature/install9

**Comment by AndreyFilchenkov** [comment]
@nickgsoft Hello Nick. Installing 9+ is supported in SIM 1.6. Please consider upgrading your version to the newer one.
