### ISSUE TITLE
Background color of SX 9 installation window differs from the rest of the window

### ISSUE THREAD

**Issue by RomanChernyk** [Sitecore/Sitecore-Instance-Manager#275]
![image](https://user-images.githubusercontent.com/12621581/66837037-0b33e400-ef6b-11e9-85a8-1a8b0cb34ee9.png)

**Comment by RomanChernyk** [comment]
Same here:

![image](https://user-images.githubusercontent.com/12621581/66838401-43d4bd00-ef6d-11e9-9f92-70d62a23fc96.png)

**Comment by AndreyFilchenkov** [comment]
Fixed via https://github.com/Sitecore/Sitecore-Instance-Manager/pull/298
