### ISSUE TITLE
Do not show Installing SIF and Prerequisites steps in the deletion dialog

### ISSUE THREAD

**Issue by RomanChernyk** [Sitecore/Sitecore-Instance-Manager#277]
The highlighted steps should not be shown in the dialog for deleting instances:

![image](https://user-images.githubusercontent.com/12621581/66838740-e2f9b480-ef6d-11e9-9b33-93dd9960161c.png)

**Comment by IvanSheyenko** [comment]
Added base logic. Further implementation depends on changes coming in #264.

**Comment by IvanSheyenko** [comment]
install sif is required. We need to ensure that it is installed to uninstall sitecore. Also, a different sif version might be required for uninstall.
Prerequisites task removed from uninstall and reinstall list.
