### ISSUE TITLE
Show site name instead of the instance name in the re-installation dialog

### ISSUE THREAD

**Issue by RomanChernyk** [Sitecore/Sitecore-Instance-Manager#279]
The highlighted text should be replaces with the site name instead of the instance name:
![image](https://user-images.githubusercontent.com/12621581/66839122-9793d600-ef6e-11e9-8737-1c065ba90a8e.png)

**Comment by AndreyFilchenkov** [comment]
Implemented via 51e3a5bf3def133a949f3ae7eb1b18b4aca8aac2
The 'environment/site' name is shown instead of the 'instance' name
