### ISSUE TITLE
SIM Updater always asks me to download an update despite I *always* click "Always yes, do not ask again"

### ISSUE THREAD

**Issue by sergeyshushlyapin** [Sitecore/Sitecore-Instance-Manager#28]
The Updater option "Always yes, do not ask again" does not work. It **will** ask me again next time a new version released.

![image](https://cloud.githubusercontent.com/assets/4719165/10365677/d61b14aa-6dcd-11e5-99e7-633c7c91ff6f.png)

**Comment by AlenPelin** [comment]
Thanks for an issue report. It is quite difficult to fix issues with updater, it is very risky (as if updater got broken you cannot upgrade broken updater) and there is not much outcome from doing that. 

So I am very sorry, but this will remain as a known issue until we move to ClickOnce way of distributing SIM.
