### ISSUE TITLE
Improve UX of Solr Configuration in Advanced Settings view

### ISSUE THREAD

**Issue by RomanChernyk** [Sitecore/Sitecore-Instance-Manager#280]
Go to Settings->Solrs->'...' and try to remove the existing Solr configuration.
It is not possible.

![image](https://user-images.githubusercontent.com/12621581/66840505-d6c32680-ef70-11e9-91be-d425d650010f.png)

**Comment by IvanSheyenko** [comment]
it is possible. just focus the line and hit delete

**Comment by RomanChernyk** [comment]
We should re-consider the way the delete operation is implemented. It is not really trivial to understand for the end user how to delete a configuration.

The options could be: add the delete button, allow to save empty values in order to remove the line, etc.
