### ISSUE TITLE
It is possible to close the Solr Configuration Editor with the validation errors

### ISSUE THREAD

**Issue by RomanChernyk** [Sitecore/Sitecore-Instance-Manager#281]
Go to Settings->Solrs->'...'.
Put something into the Name column and leave others empty.
Click Ok.

For a moment you see a red '!' sign of error, but the window is closed and the new Solr configuration is not added.

1. It must not be possible to close the window using Ok button if there are errors.
2. The user must be notified about the errors that prevent closure.
3. There should be a cancel button to close the window if the user does not want to fix errors.

**Comment by IvanSheyenko** [comment]
fixed in #280

**Comment by RomanChernyk** [comment]
@IvanSheyenko please check the following scenario:
https://www.screencast.com/t/BHemnvVNoV

**Comment by IvanSheyenko** [comment]
fixed
