### ISSUE TITLE
Add functionality that save and update information about Sitecore environments

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#282]
This task is related to the following one:
[https://github.com/Sitecore/Sitecore-Instance-Manager/issues/247](https://github.com/Sitecore/Sitecore-Instance-Manager/issues/247)

We discussed with @AndreyFilchenkov that the following functionality should be implemented:
1. Save data to **C:\Users\\<username>\AppData\Roaming\Sitecore\Sitecore Instance Manager\Profiles\Environments.json** file (see the attached [Environments.zip](https://github.com/Sitecore/Sitecore-Instance-Manager/files/3738659/Environments.zip) example) about the environment while installing Sitecore instance.
2. Update data if an instance or environment is removed.

**Comment by AndreyFilchenkov** [comment]
The functionality was implemented.
PR: https://github.com/Sitecore/Sitecore-Instance-Manager/pull/291
