### ISSUE TITLE
The context menu dialog is closed with a noticeable delay

### ISSUE THREAD

**Issue by AndreyFilchenkov** [Sitecore/Sitecore-Instance-Manager#287]
**Description:**  
The context menu dialog is closed with a noticeable delay

**Scenario:**  
1. Click 'RMB' on any SC version(SC 8.x or SC 9.x) in SIM;
2. Select `Reinstall Instance` option;

**Actual result**
The new 'Rinstalling instance ...' dialog window appears;
However, the previous 'context menu' window is being still displayed for a several seconds(in my case it is displayed for 5 seconds).

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version

**Screenshots:**
Please find the screenshot attached:
![image](https://user-images.githubusercontent.com/22079019/67094276-2c3f4380-f1bc-11e9-9f70-1a7909cca1a9.png)

**Comment by ViacheslavAfanasyev** [comment]
@AndreyFilchenkov it looks like isn't reproducible anymore
Could you please check it and close the issue.

**Comment by AndreyFilchenkov** [comment]
I have checked the issue and have seen that it is not reproducible anymore. The issue was checked on the SIM QA 1.7.0.590.
