### ISSUE TITLE
DMKO installation issue

### ISSUE THREAD

**Issue by RomanChernyk** [Sitecore/Sitecore-Instance-Manager#293]
@DmitryKolinchuk experiences the following issue when trying to install Sitecore 9.0.1. Let's investigate and find the reason.

[----------------------- CreateAppPool : AppPool -----------------------------]
**********************
Command start time: 20191029134215
**********************
PS>TerminatingError(Get-Item): "Cannot retrieve the dynamic parameters for the cmdlet. Retrieving the COM class factory for component with CLSID {688EEEE5-6A7E-422F-B2E1-6AF00DC944A6} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))."
>> TerminatingError(Invoke-AppPoolTask): "Cannot retrieve the dynamic parameters for the cmdlet. Retrieving the COM class factory for component with CLSID {688EEEE5-6A7E-422F-B2E1-6AF00DC944A6} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))."
Install-SitecoreConfiguration : Cannot retrieve the dynamic parameters for the cmdlet. Retrieving the COM class factory 
for component with CLSID {688EEEE5-6A7E-422F-B2E1-6AF00DC944A6} failed due to the following error: 80040154 Class not 
registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
At line:66 char:1
+ Install-SitecoreConfiguration @installParams  -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Install-SitecoreConfiguration
[TIME] 00:00:04
**********************
Windows PowerShell transcript end
End time: 20191029134215
**********************

**Comment by IvanSheyenko** [comment]
https://stackoverflow.com/questions/40031846/new-webbinding-cannot-retrieve-the-dynamic-parameters-for-the-cmdlet
Looks like this has something to do with the bitness of the process. Do you have both PSx64 and x32 on the machine?
Does it happen when running from VS or running sim directly or both?

**Comment by DmitryKolinchuk** [comment]
@IvanSheyenko I have both PS x64 and x86 installed. I tested the installation by running SIM from Visual Studio, so I will try to run it directly.

**Comment by DmitryKolinchuk** [comment]
After further investigation, it appeared that the cause of the issue is that the Platform Target was set to x86 (it should be set to Any CPU) in my local SIM.Tool project.
