### ISSUE TITLE
Refactor the code related to buttons

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#299]
In the current SIM implementation only buttons (ButtonDefinition) have the following methods (defined in IMainWindowButton) that are binded to FrameworkElement:

- IsEnabled
- IsVisible
- OnClick

However, groups (GroupDefinition) and menu items (they are also represented as ButtonDefinition) don't have the same binding which prevents to control their state in the appropriate manner.
So, the existing code should be refactored to add necessary bindings.

**Comment by AndreyFilchenkov** [comment]
Implemented in PR: #469
