### ISSUE TITLE
9.0 uninstall does not patch files

### ISSUE THREAD

**Issue by IvanSheyenko** [Sitecore/Sitecore-Instance-Manager#307]
uninstall of 9.0 does not add uninstall tasks as topology cannot be resolved
https://www.screencast.com/t/iOsZ3cwM

**Comment by IvanSheyenko** [comment]
We should not use topology to determine which tasks to add as it is possible to install not standard topology like 2 CDs. Uninstall tasks should be generated based on install tasks.

**Comment by AndreyFilchenkov** [comment]
> [Bug] uninstall of 9.0 does not add uninstall tasks as topology cannot be resolved
> https://www.screencast.com/t/iOsZ3cwM

I was not able to reproduce the issue. Could you provide the scenario?


> [Wish] We should not use topology to determine which tasks to add as it is possible to install notstandard topology like 2 CDs. Uninstall tasks should be generated based on install tasks.

It was agreed that SIM supported installing officially released SC9 topologies/versions using WDP packages from the dev.sitecore.net.
So the new approach of generating uninstall tasks should be considered as wish and should be moved from the current milestone (1.6.0) to a further one.

**Comment by AndreyFilchenkov** [comment]
The bug was fixed. The current topology is got based on the configuration files names in the installation folder (e.g. sitecore-XP0).
