### ISSUE TITLE
Embed NuGet Generator

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#31]

**Comment by SaintSkeeta** [comment]
Nice work.
I found that the packages created using this through SIM are Super-granular (i.e one package per DLL). I prefer the Standalone Nuget Package Generator where there are some defined packages for development that bring in multiple DLLs.
Will this eventually be implemented?

**Comment by AlenPelin** [comment]
I was thinking about that approach and came to conclusion that it is very difficult to maintain all these packs - you should know dependencies precisely or develop some sophisticated logic that I am not sure how to develop. The current implementation is done according concept of spending minimum resources to get maximum outcome. 

SIM is open source project so you are welcome to fork and develop this logic - I will be glad to review pull request. 

My next aim here is to focus on Sitecore.Bootcamp instead that will reuse this packages, and embed it into this generator and SIM.
