### ISSUE TITLE
Unable to delete Sitecore 9 instance when package is located under subfolder

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#310]
**Steps to reproduce:**
1. Set "Local repository" to "C:\Sitecore"
2. Add the "Sitecore 9.0.0 rev. 171002 (WDP XM1 packages).zip" package to the "C:\Sitecore\ZIP" folder.
3. Install Sitecore 9.0.0 rev. 171002 XM1.
4. Delete Sitecore 9.0.0 rev. 171002 XM1.
Click the "Yes" button after appearing the "Overwrite?" dialog box:
![Overwrite](https://user-images.githubusercontent.com/20965100/69729366-d781d780-112e-11ea-82c4-53244c2365d5.png)

**Result:** the following error occurs:
![sc900xm1test1_delete_error](https://user-images.githubusercontent.com/20965100/69723410-207f5f00-1122-11ea-8c3c-5c07ca3badda.png)

**Notes:**
The issue occurs since SIM tries to locate the "Sitecore 9.0.0 rev. 171002 (WDP XM1 packages).zip" package under the "C:\Sitecore" root instead of "C:\Sitecore\ZIP".
The stack trace is also attached:
[StackTrace.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/3896834/StackTrace.txt)

**Comment by IvanSheyenko** [comment]
#308 most likely fixes this as uninstall no longer relies on the original sitecore archive.

**Comment by AndreyFilchenkov** [comment]
Fixed
