### ISSUE TITLE
Incorrect nesting of instances in the list after installing Sitecore 9.

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#311]
Currently, there is no stable scenario, but sometimes after installing Sitecore 9 the following behavior can be observed:
![List](https://user-images.githubusercontent.com/20965100/69731534-bae79e80-1132-11ea-93b6-d26d7860286a.png)

The issue disappears after refreshing sites, so it doesn't look to be related to incorrect data in the Environments.json file.

**Comment by IvanSheyenko** [comment]
can reproduce when using the search bar or button

**Comment by DmitryKolinchuk** [comment]
@IvanSheyenko @AndreyFilchenkov I tried to use search but wasn't able to reproduce the issue. @IvanSheyenko could you please provide a screencast of how you were able to reproduce it? Anyway, I will test your [fix](https://github.com/Sitecore/Sitecore-Instance-Manager/pull/321) and let you know if it helps.

**Comment by DmitryKolinchuk** [comment]
@IvanSheyenko @AndreyFilchenkov I didn't face this issue while installing, uninstalling and deleting all topologies of Sitecore XP 9.0.0, so it looks like the fix works well.

**Comment by AndreyFilchenkov** [comment]
The issue has been fixed.
