### ISSUE TITLE
Unnecessary dialog box appears when folder with scripts is created

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#312]
**Steps to reproduce:**
1. Install Sitecore 9 (e. g. Sitecore XP 9.0.0 XM1).
2. Delete the "Sitecore 9.0.0 rev. 171002 (WDP XM1 packages)" folder with generated scripts.
3. Repeat the first step.

**Result:** the following dialog box appears despite the "Sitecore 9.0.0 rev. 171002 (WDP XM1 packages)" folder is created:
![Install](https://user-images.githubusercontent.com/20965100/69731956-76103780-1133-11ea-8957-696c37fd648c.png)

**Comment by IvanSheyenko** [comment]
As I recall this message is about already existing sitecore deploy root folder (with websites), not installation files. Please check.

**Comment by AndreyFilchenkov** [comment]
The 'Sitecore deploy root folder' is being removed now. The issue is not reproducible anymore.
