### ISSUE TITLE
Instances are collapsed after performing any right-click action

### ISSUE THREAD

**Issue by ViacheslavAfanasyev** [Sitecore/Sitecore-Instance-Manager#319]
Instances are collapsed after performing any right-click action
See screencast with right-click action.
https://www.screencast.com/t/LIdkheoAy8b

**Comment by DmitryKolinchuk** [comment]
@ViacheslavAfanasyev I am not able to reproduce the issue using the **feature/milestone/1.6.1** branch with the latest 9005683 commit:
[https://www.screencast.com/t/IUPauPjGfHp9](https://www.screencast.com/t/IUPauPjGfHp9)

**Comment by ViacheslavAfanasyev** [comment]
@DmitryKolinchuk looks like if fixed :-)
