### ISSUE TITLE
2 errors after installation

### ISSUE THREAD

**Issue by traxswe** [Sitecore/Sitecore-Instance-Manager#32]
I have a problem with the SIM-tool. I opened the zip-file and ran the tool SIM.tool.exe in admin mode. It ran through the entire setup process. Afterwards i keep getting an error each time it opens up something (like a menu element). It produces another error each time i try to import the Sitecore insurecore8-solution.
A third issue is also that the SIM-tool asks me to open the log-folder but when i accept, it then just show the documents folder in Windows. I did however found the log files under appdata/roaming/sitecore and i have added a link to then below. Git did not allow me to upload text files even though it says it should.

The laptop i try to install on is a new HP Elitebook 840 (I7, 8GB ram) with Windows 8.1. It is a complete new OS installation and the only things installed, besides the OS, is MS Office, SQL Server Express and Visual Studio,

<img width="351" alt="download package error" src="https://cloud.githubusercontent.com/assets/2046175/10448034/291820d4-718a-11e5-9ac5-13a279909edf.PNG">
<img width="365" alt="installation result" src="https://cloud.githubusercontent.com/assets/2046175/10448035/291ec4b6-718a-11e5-800b-9dcd674ebe2e.PNG">

Logs: https://drive.google.com/file/d/0B970L_RfZ0yTTmZ3eXF6cEFHcVU/view?usp=sharing

If anyone is in the Stockholm region, i can show it live.

**Comment by AlenPelin** [comment]
1. Make sure that you installed IIS. 
2. Make sure that you configured SQL Server correctly according to [Troubleshooting](https://github.com/Sitecore/Sitecore-Instance-Manager/wiki/Troubleshooting) section
3. Try to use [latest QA build](http://dl.sitecore.net/updater/1.1/sim/qa2/download.txt)

**Comment by traxswe** [comment]
The IIS was stopped and then it did not work. Once started it worked great.
