### ISSUE TITLE
Root folder is not deleted after Sitecore 9 uninstall

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#322]
**Steps to reproduce:**
1. Install Sitecore 9 with the "sc9test" site name.
2. Delete the installed Sitecore 9.
3. Check the location folder.

**Result:** the "sc9test" empty folder exists.

**Comment by AndreyFilchenkov** [comment]
@DmitryKolinchuk  Could yu please re-test?

**Comment by DmitryKolinchuk** [comment]
@AndreyFilchenkov I tested the scenario using Sitecore XP 9.0.1 XM1, XP0 and XP1 and it works as expected, so the issue can be closed.
