### ISSUE TITLE
White install window when click to install a new instance

### ISSUE THREAD

**Issue by ViacheslavAfanasyev** [Sitecore/Sitecore-Instance-Manager#327]
There is a white window when you click to install a new instance
Screencast: https://www.screencast.com/t/5Cwfwfo88Tm0

It's kind of a performance issue and looks ugly.

**Comment by AndreyFilchenkov** [comment]
The issue was closed via PR: https://github.com/Sitecore/Sitecore-Instance-Manager/pull/334
