### ISSUE TITLE
sitecore-XP1-cm-dds-patch action fails if the CM site name is non-default

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#328]
**Steps to reproduce:**
Install Sitecore XP 9.0.1 XP1 and change the **SiteName** parameter to **$SqlDbPrefix+"CM.my"** for Sitecore-xp1-cm in the in the Advanced installation parameters dialog box.

**Result:** sitecore-XP1-cm-dds-patch action fails (see the attached [sitecore-XP1-cm-dds-patch.191205.log](https://github.com/Sitecore/Sitecore-Instance-Manager/files/3927006/sitecore-XP1-cm-dds-patch.191205.log) file for more details).
According to log, the issue occurs because global **sc901xp1test1CM.local** site name is used instead of **sc901xp1test1CM.my**.

![image](https://user-images.githubusercontent.com/20965100/70236502-b6903680-176d-11ea-864d-05a06b5a0b96.png)

![image](https://user-images.githubusercontent.com/20965100/70236476-a5472a00-176d-11ea-86e4-372a3f4cb126.png)

**Comment by DmitryKolinchuk** [comment]
The issue is also reproduced with Sitecore XP 9.0.2 XP1.

**Comment by IvanSheyenko** [comment]
@DmitryKolinchuk @AndreyFilchenkov 
You changed site name parameter for an individual task (CM). Changes to individual task parameters do not affect the parameters of other tasks. DDS patch task has SiteName parameter that must point to CM. 
Changing advanced installation parameters assumed that user good level of understanding of the system.

What we can improve here:
1. create a corresponding validator
2. Introduce CMSiteName global parameter and reference it from all other places. So CM name can be updated on the global tab and change is propagated to other tasks. However, if CM site name is changed on individual task level it will still fail.
3. Create a C# abstraction level to maintain parameters dependencies that cannot be covered by Powershell variables.

What do you think ?

**Comment by DmitryKolinchuk** [comment]
@IvanSheyenko as for me all options sound good. However, the first one looks more valid. We need to inform a user somehow that this parameter should be also changed in DDS.

**Comment by AndreyFilchenkov** [comment]
Combination 1 and 2 looks good.

**Comment by ViacheslavAfanasyev** [comment]
1 - is the easiest way to prevent the error in case a user runs validators.
2 - doesn't resolve the current issue in case a user updates the value for CM task
3 - sounds well, in this case, no matter how hard a user tries to change the value, it won't fail.
