### ISSUE TITLE
Redesign the 'Deleting instances' dialog

### ISSUE THREAD

**Issue by AndreyFilchenkov** [Sitecore/Sitecore-Instance-Manager#333]
1. The instance name should be displayed using 'label' control;
2. Remove the Solr label and related dropdown;

![image](https://user-images.githubusercontent.com/22079019/70545308-0b6cec00-1b76-11ea-84eb-e1f38603d968.png)

**Comment by IvanSheyenko** [comment]
Redesigned to this:
![image](https://user-images.githubusercontent.com/13461196/70659447-1aaf7080-1c2e-11ea-9bd2-2fb03168420c.png)

@AndreyFilchenkov @RomanChernyk  please check

**Comment by RomanChernyk** [comment]
Maybe let's leave environment name? Just for the user to be sure what their delete.

**Comment by IvanSheyenko** [comment]
New variant:
![image](https://user-images.githubusercontent.com/13461196/70832541-562f7380-1dc3-11ea-9fb1-54bc97c323f5.png)

@RomanChernyk  @AndreyFilchenkov please check

**Comment by AndreyFilchenkov** [comment]
Looks good. Thank you.

**Comment by AndreyFilchenkov** [comment]
Implemented via PR: https://github.com/Sitecore/Sitecore-Instance-Manager/pull/345
