### ISSUE TITLE
NullReferenceException when installing XP and not defining some fields which are required

### ISSUE THREAD

**Issue by ArtemNizelnyk** [Sitecore/Sitecore-Instance-Manager#337]
**Description:**  
NullReferenceException is thrown when installing XP and not defining some fields which are required

**Scenario:**  
1.  Click "Get Sitecore";
2. Select Sitecore XP 9.3 and wait until the download is finished.
3. Click install SC XP 9 
4. In Installing new instance dialog set a site name to "sc930"
5. Click Next;
**Actual result:**  
NullReference exception is thrown;

**Expected Result:**  
The user is notified that the required field is not defined.

**Issue is actual**  
I hereby confirm the issue is new:
* all [prerequisites](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#prerequisites) are met.
* it is not a [known issue](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#knwon-ssue)
* it was not discussed before (I used GitHub Issues search)

**Valid for QA**  
I hereby confirm the issue is reproducible on the latest QA version [PUT HERE EXACT VERSION NUMBER]
which was downloaded today from http://dl.sitecore.net/updater/qa/sim

**Valid for DEV**  
I hereby confirm the issue is reproducible on the latest DEV version [1.6.0.431]
which was downloaded today from https://sitecore.box.com/s/sbxk4442ox324db7eyfqjjpopipqib1a

**Screenshots:**
Please find screenshots attached.
![image](https://user-images.githubusercontent.com/13044795/70766300-4f3f3b80-1d98-11ea-92a8-304e006573f3.png)

**Attachments:**  
Please find attached latest log files:
```
[2019-12-13.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/3958833/2019-12-13.txt)
[2019-12-13_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/3958834/2019-12-13_DEBUG.txt)

```

**Comment by ArtemNizelnyk** [comment]
the problem was an empty Solr field.

**Comment by ArtemNizelnyk** [comment]
You might want to use it a wish to enable Validation

**Comment by IvanSheyenko** [comment]
fixed

**Comment by AndreyFilchenkov** [comment]
Fixed via PR: https://github.com/Sitecore/Sitecore-Instance-Manager/pull/340
