### ISSUE TITLE
ArgumentNullException appears at first run of the installation

### ISSUE THREAD

**Issue by ViacheslavAfanasyev** [Sitecore/Sitecore-Instance-Manager#342]
**Steps to reproduce:**
1. Remove AppData\Roaming\Sitecore\Sitecore Instance Manager folder of just AppData\Roaming\Sitecore\Sitecore Instance Manager\Profiles\profile.xml
2. Run SIM
3. Try to install instance(at least 9 one)

ArgumentNullException appears. See the screencast https://www.screencast.com/t/rWdkJ1le

**Comment by AndreyFilchenkov** [comment]
The bug was fixed via PR: #343
