### ISSUE TITLE
Add support for Sitecore 8.1

### ISSUE THREAD

**Issue by jasonchester** [Sitecore/Sitecore-Instance-Manager#35]
Released on October 20, 2015

**Comment by marcduiker** [comment]
You can rename the zip file to Sitecore 8__.__1 rev__.__ 151003.zip and then you can install it.

**Comment by AlenPelin** [comment]
What is the problem with 8.1? Did you try to download it with SIM's "Get Sitecore" button?

**Comment by AlenPelin** [comment]
I double checked that in [latest SIM 1.4](http://dl.sitecore.net/updater/1.1/sim/qa2/SIM 1.4 rev. 151019.zip) Get Sitecore button allows to download 8.1 and it works fine after that.

**Comment by marcduiker** [comment]
@AlenPelin Ah I downloaded it manually and added it to the local repo.
