### ISSUE TITLE
SIM users can face the Certificate installation errors

### ISSUE THREAD

**Issue by AndreyFilchenkov** [Sitecore/Sitecore-Instance-Manager#350]
SIM users can face Certificate installation errors described in the following KB article:
https://kb.sitecore.net/articles/699694

We should prevent appearing such issues.

**Comment by IvanSheyenko** [comment]
@AndreyFilchenkov 
We already use different root certificates for SIF 1.2.1 and 2+. This should not happen in SIM. Have you encountered this?
