### ISSUE TITLE
Make sure error messeges have a friendly look

### ISSUE THREAD

**Issue by Detnoi** [Sitecore/Sitecore-Instance-Manager#351]
1. Avoid posting a stack trace to the error message.
2. If error scenario is clear it should be described in the alert with a suggestion how to fix it.
3. If error scenario is unknown - alert should suggest to create a ticket on github.

In all cases information about error should be added to logs.

**Comment by IvanSheyenko** [comment]
I have removed the stack from the error messages.
![image](https://user-images.githubusercontent.com/13461196/74286836-a1e49780-4cf6-11ea-95dd-12d03beeadcd.png)
Is this friendly enough?

Powershell can throw the same exception for multiple reasons and providing a suggestion on how to fix it requires SIF log analysis. Many errors will be prevented by validation #365.

**Comment by AndreyFilchenkov** [comment]
Implemented in PR #372
