### ISSUE TITLE
No way to add SOLR from the settings if there is no configure solr

### ISSUE THREAD

**Issue by ViacheslavAfanasyev** [Sitecore/Sitecore-Instance-Manager#355]
Steps:
1. Open SIM
2. Go to Setting
3. Click ... to add SOLR

Results: UI is corrupted, no way to add it:
![image](https://user-images.githubusercontent.com/9393016/73097163-7ec38680-3eb4-11ea-8eef-73ca8905ad72.png)

Expected results: UI isn't corrupted. You can add SOLR.

**Comment by AndreyFilchenkov** [comment]
The issue has been closed via PR #368
