### ISSUE TITLE
Make service field of the SOLR setting is mandatory as it can cause the issue

### ISSUE THREAD

**Issue by ViacheslavAfanasyev** [Sitecore/Sitecore-Instance-Manager#356]
Make service field of the SOLR setting is mandatory as it can cause the issue
![image](https://user-images.githubusercontent.com/9393016/73098884-4e7de700-3eb8-11ea-93b3-c2d662f271fc.png)

**Comment by IvanSheyenko** [comment]
To clarify, this is about the issue when you try to install 9.1+ without solr service. It uses SIF default value which is not empty and fails as service does not exist

**Comment by IvanSheyenko** [comment]
After investigation, it appears that solr service is mandatory :/

**Comment by IvanSheyenko** [comment]
The original issue is specific to a machine and is caused by the broken service with the same name as the default SIF value.

**Comment by IvanSheyenko** [comment]
Validator for solr service should be created.

**Comment by IvanSheyenko** [comment]
Validator added to check that service does not exist or is running.

**Comment by AndreyFilchenkov** [comment]
Validator was added
