### ISSUE TITLE
unable to insatall Sitecore Insatance Manager

### ISSUE THREAD

**Issue by Shan-Mohammad** [Sitecore/Sitecore-Instance-Manager#357]
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!! READ THIS CAREFULLY !!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                     !!
!! 1. Do not remove any sections from this template    !!
!! 2. Do not create issue without SIM version AND logs !!
!! 3. Remove this disclaimer before posting issue      !!
!!                                                     !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Description:**  
The issue is...

**Scenario:**  
1.  
2. 
3. 

**Issue is actual**  
I hereby confirm the issue is new:
* all [prerequisites](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#prerequisites) are met.
* it is not a [known issue](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#knwon-ssue)
* it was not discussed before (I used GitHub Issues search)

**Valid for QA/DEV**  
I hereby confirm the issue is reproducible on the latest QA/DEV version [PUT HERE EXACT VERSION NUMBER]

**Screenshots:**
Please find screenshots attached.

**Attachments:**  
Please find attached latest log files from this folders:
```
%APPDATA%\..\Roaming\Sitecore\Sitecore Instance Management\logs 
%APPDATA%\..\Roaming\Sitecore\Sitecore Instance Manager-QA\logs 
```

**Comment by AndreyFilchenkov** [comment]
This issue has been closed since it duplicates issue #358
