### ISSUE TITLE
its Saying"unable retrieve application files. File corrupted in deployment"

### ISSUE THREAD

**Issue by Shan-Mohammad** [Sitecore/Sitecore-Instance-Manager#358]
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!! READ THIS CAREFULLY !!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                     !!
!! 1. Do not remove any sections from this template    !!
!! 2. Do not create issue without SIM version AND logs !!
!! 3. Remove this disclaimer before posting issue      !!
!!                                                     !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Description:**  
The issue is...

**Scenario:**  
1.  
2. 
3. 

**Issue is actual**  
I hereby confirm the issue is new:
* all [prerequisites](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#prerequisites) are met.
* it is not a [known issue](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#knwon-ssue)
* it was not discussed before (I used GitHub Issues search)

**Valid for QA/DEV**  
I hereby confirm the issue is reproducible on the latest QA/DEV version [PUT HERE EXACT VERSION NUMBER]

**Screenshots:**
Please find screenshots attached.

**Attachments:**  
Please find attached latest log files from this folders:
```
%APPDATA%\..\Roaming\Sitecore\Sitecore Instance Management\logs 
%APPDATA%\..\Roaming\Sitecore\Sitecore Instance Manager-QA\logs 
```

**Comment by AndreyFilchenkov** [comment]
@Shan-Mohammad 
Thank you for reporting the issue.

Could you please provide a bit more information about the issue you faced with? 
1. A name/version of Operation System
2. What web link did you use to install SIM?
3. Please provide the entire error output reported by the ClickOnce installer.

**Comment by AndreyFilchenkov** [comment]
Closed as obsolete. Please feel free to reopen the issue if it is still reproducible.
