### ISSUE TITLE
Installation is failed due to the long path/filename

### ISSUE THREAD

**Issue by OlegBraginskyy** [Sitecore/Sitecore-Instance-Manager#359]
**Description:**  
Installation is failed due to the long path/filename

**Scenario:**  
1.  Install Sim QA (Default path to the repository is `C:\Users\obr\AppData\Roaming\Sitecore\Sitecore Instance Manager-QA\Repository`)
2. Download any Sitecore package using the `Get Sitecore` tool (for example `Sitecore 9.1.1`)
3. Run Sitecore installation

**Issue is actual**  
I hereby confirm the issue is new:
* all [prerequisites](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#prerequisites) are met.
* it is not a [known issue](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#knwon-ssue)
* it was not discussed before (I used GitHub Issues search)

**Valid for QA/DEV**  
I hereby confirm the issue is reproducible on the latest QA version Sim QA 1.6.0.465

**Screenshots:**
https://www.screencast.com/t/ZkqJQZnfx

**Attachments:**  
[2020-01-28.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/4121339/2020-01-28.txt)
[2020-01-28_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/4121340/2020-01-28_DEBUG.txt)

**Comment by DmitryKolinchuk** [comment]
The issue is not reproduced if download a package from [https://dev.sitecore.net/](https://dev.sitecore.net/) but not using the `Get Sitecore` tool.
