### ISSUE TITLE
Long running task during the installation

### ISSUE THREAD

**Issue by OlegBraginskyy** [Sitecore/Sitecore-Instance-Manager#360]
**Description:**  
Installation is failed during unpacking installation files.

**Scenario:**  
1. Install Sim QA
2. Download any Sitecore package (foe example `Sitecore 9.1.1`)
3. Run Sitecore installation

**Issue is actual**  
I hereby confirm the issue is new:
* all [prerequisites](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#prerequisites) are met.
* it is not a [known issue](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#knwon-ssue)
* it was not discussed before (I used GitHub Issues search)

**Valid for QA/DEV**  
I hereby confirm the issue is reproducible on the latest QA version Sim QA 1.6.0.465

**Screenshots:**
https://www.screencast.com/t/1EqjnABe28p

**Attachments:**  
[2020-01-28.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/4121358/2020-01-28.txt)
[2020-01-28_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/4121359/2020-01-28_DEBUG.txt)

**Comment by AndreyFilchenkov** [comment]
The issue is still reproducible, commit: c4c19f50705187bbf1db418fb3096424fff8284a

Updated scenario:

1. Install Sim QA
1. Download any Sitecore package **for Azure AppService** [for example Sitecore 9.1.1 rev. 002459 (WDP XPSingle packages).zip]
1. Run Sitecore installation
