### ISSUE TITLE
Cannot list the sites when SIM not running as administrator

### ISSUE THREAD

**Issue by ykurniawan** [Sitecore/Sitecore-Instance-Manager#37]
It is also nice if the app running not as administrator, it should display info message when failed to list the sites at SIM.Adapters.WebServer.WebServerManager.WebServerContext.get_Sites(). I found this issue at the first time I run SIM, cannot list any site. Anyway, thank you @Brad-Christie for the ifrunningasadministrator indicator.  Thanks.

**Comment by AlenPelin** [comment]
SIM manifest does not allow to run SIM without administrative permissions. Were you able to bypass that?

**Comment by Brad-Christie** [comment]
Frequently, yes. I can get SIM to run without UAC. It may just require a change to manifest for newer versions of windows, but server 2012 doesn't require it.

Brad Christie
Sitecore
Solutions Architect
55 S. Commercial St., Manchester, NH 03103

**Comment by ykurniawan** [comment]
Yes, On my Windows 8.1 without UAC, SIM can run but cannot list the sites,
also happen on my Windows  10 with UAC.

**Comment by AlenPelin** [comment]
Should have already been fixed in latest QA build http://dl.sitecore.net/updater/qa/sim

**Comment by ykurniawan** [comment]
AC: System will ask for permission before running SIM when UAC is turned on. [PASSED]
