### ISSUE TITLE
The exception occurs when the 'DO_NOT_TRUST_SitecoreRootCert' certificate is expired.

### ISSUE THREAD

**Issue by sc-ArtemChunikhin** [Sitecore/Sitecore-Instance-Manager#381]
**Description:**  
The exception occurs during installation Sitecore 9.0 Update-2 when the 'DO_NOT_TRUST_SitecoreRootCert' certificate is expired.

**Scenario:**  
1.  Make sure that the 'DO_NOT_TRUST_SitecoreRootCert' certificate has expired.
2. Start installing a new instance of Sitecore 9.0 Update-2.

**Result**: In the process of installation, the exception related to certificate expiration will occur at the 'xconnect-xp0' installation step.

**Issue is actual**  
I hereby confirm the issue is new:
* all [prerequisites](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#prerequisites) are met.
* it is not a [known issue](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#knwon-ssue)
* it was not discussed before (I used GitHub Issues search)

**Valid for QA/DEV**  
I hereby confirm the issue is reproducible on the latest DEV version 1.6.0.431

**Screenshots:**

**Attachments:**

**Comment by AndreyFilchenkov** [comment]
Implemented ``` CertificateValidator.cs ``` that tries to find certificates related to the installation tasks and checks if they are valid. 
PR: #387

**Comment by AndreyFilchenkov** [comment]
The issue is reproducible on: c4c19f50705187bbf1db418fb3096424fff8284a commit.
The cert validators do not validate(show any warnings/errors) even in case the  'DO_NOT_TRUST_SitecoreRootCert' is expired.
