### ISSUE TITLE
Validate existing database names

### ISSUE THREAD

**Issue by sc-ArtemKosohov** [Sitecore/Sitecore-Instance-Manager#386]
Consider adding a check for database names before installation.

Specific scenario:
I have a set of databases with the following naming mask sc930_* for Sitecore XP 9.3 instance which was installed using SIA.
While installing a new XP1 Sitecore 9.3 instance with the "sc930test" name I got the following error: 
![image](https://user-images.githubusercontent.com/52958875/76313382-82349500-62dd-11ea-9e06-736a3ed56eb4.png)

with the following exception in the installation log:
[WebDeploy]:[Path] C:\Program Files\iis\Microsoft Web Deploy V3\msdeploy.exe
msdeploy.exe : Error: .Net SqlClient Data Provider: Msg 5061, Level 16, State 1, Line 5 ALTER DATABASE failed because a 
lock could not be placed on database 'sc930_MarketingAutomation'. Try again later.
At C:\Program Files\WindowsPowerShell\Modules\SitecoreInstallFramework\2.2.0\Public\Tasks\Invoke-CommandTask.ps1:31 

Which is strange considering the fact that a new set of sc930test_* databases was successfully created.

**Comment by AndreyFilchenkov** [comment]
We should add the validator:
- ensure that the SQL server does not contain the databases with the $sqldbprefix prefix;
