### ISSUE TITLE
Rewrite SIM Telemetry API to have an event handler that informs when the tracking is finished

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#401]
For more information about the issue, please refer to the following SCLA PBI:
[https://dev.azure.com/Sitecore-PSS/Sitecore%20log%20analyzer/_workitems/edit/2197](https://dev.azure.com/Sitecore-PSS/Sitecore%20log%20analyzer/_workitems/edit/2197)

**Comment by RomanChernyk** [comment]
Not needed any longer. Let's cancel.
