### ISSUE TITLE
IIS site/app pool/folder validation

### ISSUE THREAD

**Issue by AndreyFilchenkov** [Sitecore/Sitecore-Instance-Manager#411]
- IIS should not have sites/app pools with $sqldbprefix;
- the wwwroot folder should not have a folder with $sqldbprefix;

**Comment by DmitryKolinchuk** [comment]
Discussed with @AndreyFilchenkov that the second point is covered by the following existing validation:
![image](https://user-images.githubusercontent.com/20965100/79562799-434fe700-80b4-11ea-995d-e6649758c96c.png)
