### ISSUE TITLE
Browse Sitecore Website button does not work for Identity Service

### ISSUE THREAD

**Issue by RomanChernyk** [Sitecore/Sitecore-Instance-Manager#412]
**Description:**  
Browse Sitecore Website button does not work for Identity Service

**Scenario:**  
1. Install Sitecore 9.3 (XP single in my case)
2. Right Click on Identity Service instance
3. Select Browse Sitecore Website button

Result: nothing happens.

**Issue is actual**  
I hereby confirm the issue is new:
* all [prerequisites](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#prerequisites) are met.
* it is not a [known issue](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/develop/README.md#knwon-ssue)
* it was not discussed before (I used GitHub Issues search)

**Attachments:**  
Please find attached latest log files from this folders:
[2020-04-10.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/4461071/2020-04-10.txt)
[2020-04-10_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/4461072/2020-04-10_DEBUG.txt)

**Comment by DmitryKolinchuk** [comment]
The same issue is reproduced for the **Open web.config file** command.

**Comment by AndreyFilchenkov** [comment]
Closed by PR #442
