### ISSUE TITLE
CertificateValidator shows ERROR for completely different certificate if it's invalid

### ISSUE THREAD

**Issue by ViacheslavAfanasyev** [Sitecore/Sitecore-Instance-Manager#419]
There is screencast with the issue: https://www.screencast.com/t/KhU5eBF2rdh
There are debug values from the validator: https://www.screencast.com/t/CdBBen2hMvk

this.FindCertificates(search); looks like tries to find the certificates using contains condition.

**Comment by IvanSheyenko** [comment]
This behavior is determined by MS certificates API it searches by contains, not an exact match. Unfortunately, there is no easy way to filter certificates by exact match. Avoid creating certificates with similar names.

**Comment by ViacheslavAfanasyev** [comment]
> This behavior is determined by MS certificates API it searches by contains, not an exact match. Unfortunately, there is no easy way to filter certificates by exact match. Avoid creating certificates with similar names.

fcollection.SelectMany(predicate) isn't case?
