### ISSUE TITLE
The instance of SQL Server cannot be reached

### ISSUE THREAD

**Issue by owingruters** [Sitecore/Sitecore-Instance-Manager#42]
Hi,

I am running SQL Server Express 2012 on win 10.
For SIM 1.4 I am using connectionstring: Data Source=(LocalDb)\MSSQLLocalDB;Integrated Security=True, but also tried SQL Server authentication with both sa and a newly created admin account. Every time I get the message: "The instance of SQL Server cannot be reached"

The database name is OK, because when I change it I get the default message when SQL server cannot be found (a network related... blabla).
Also with all connectionstrings that fail in SIM, I am able to logon to the database from both SQL Server management studio and Visual Studio.

Is there some issue in the conn string, or something else?

Regards

**Comment by AlenPelin** [comment]
Integrated Security is not supported. Make sure that SQL Server service uses NETWORK SERVICE user account.

**Comment by owingruters** [comment]
Hi Alen,

Thanx for your answer. I know that integrated sec does not work so I also tried multiple SQL Authentication account (sa and a new one), but that also does not work. Should I do something to make these SQL accounts run under the Network service and if so how do I do that. If not, what should be the conn string?

**Comment by AlenPelin** [comment]
I think that LocalDB could be unsupported as well, I've never used it before and if they changed something comparing to full version of SQL then it will not work

**Comment by Brad-Christie** [comment]
@AlenPelin I've seen LocalDb (Denali) used before, but I don't think it's officially supported.

@owingruters: To my knowledge, your connection string should resemble something of the following:

    Data Source=(LocalDb)\v11.0;AttachDbFilename=\inetpub\wwwroot\instancename\Data\Sitecore_Core.mdf;User Id=sa;Password=secret;

The important pieces to note:
* When using LocalDb, you need to use `(LocalDb)\v11.0` to specify version.
* You should attach the existing Sitecore databases by supplying an `AttachDbFilename` parameter.
* Supply a `User Id` & `Password` that relate to your LocalDb instance.

**Comment by AlenPelin** [comment]
@Brad-Christie thanks for help here. As long as LocalDB might work in Sitecore, SIM will not allow to use it as it transforms it during applying to a Sitecore instance.

**Comment by DmitryKolinchuk** [comment]
Closed since the issue is outdated.
