### ISSUE TITLE
The "Value cannot be null" error occurs if cancel validation

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#426]
**Scenario:**  
1. Open SIM and install, for example, Sitecore 9.3 XP1.
2. Make sure that the `Perform installation parameters validation` checkbox is checked.
3. Click the `Install` button.
4. Click the `Cancel` button in the appeared `Running validation` dialog box.

**Result:** the "Value cannot be null" error occurs.

**Valid for QA/DEV**  
I hereby confirm the issue is reproducible on the latest QA/DEV version.
Commit: 0269722f6b5ceb29502a0c00c314cbda64274e6c [0269722]

**Screenshots:**
Please find screenshot attached.
![image](https://user-images.githubusercontent.com/20965100/82037507-e93e4380-96aa-11ea-841a-e403dc5e4689.png)

**Attachments:**  
Please find attached latest log file :
[2020-05-15.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/4633621/2020-05-15.txt)

**Comment by AndreyFilchenkov** [comment]
Updated scenario:
1. Open SIM and install, for example, Sitecore 9.3 XP1.
1. Make sure that the `Perform installation parameters validation` checkbox is checked.
1. Click the `Cancel` button in the appeared `Running validation` dialog box.
1. Click the `Install` button.
