### ISSUE TITLE
NullReferenceException occurs in GetParamNames

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#427]
**Scenario:**  
1. Open SIM and install, for example, Sitecore 9.3 XP1.
2. Make sure that the `Perform installation parameters validation` checkbox is checked.
3. Click the `Install` button.

**Result:** `Validation results` contain `NullReferenceException` error that occurred in the `GetParamNames` method of `BaseValidator`.

**Valid for QA/DEV**  
I hereby confirm the issue is reproducible on the latest QA/DEV version.
Commit: 0269722f6b5ceb29502a0c00c314cbda64274e6c [0269722]

**Screenshots:**
Please find screenshots attached.
![image](https://user-images.githubusercontent.com/20965100/82057451-03d4e480-96cc-11ea-8b93-b11925b06e6d.png)

![image](https://user-images.githubusercontent.com/20965100/82056743-0aaf2780-96cb-11ea-8737-5d4fae531a35.png)

**Comment by AndreyFilchenkov** [comment]
It is not reproducible in my local environment on c4c19f50705187bbf1db418fb3096424fff8284a commit.
@DmitryKolinchuk could you please recheck the issue on the latest milestone/1.6.1?

**Comment by DmitryKolinchuk** [comment]
@AndreyFilchenkov the issue is not reproduced using fa6ccb3fba2d3373ac38054523d03e5154b7a3c0  commit.

**Comment by IvanSheyenko** [comment]
This is fixed in the latest codebase in ValidationFactory:
if (definition.Data != null)
        {
          validator.Data = definition.Data;
        }
the if condition was missing.
