### ISSUE TITLE
Context menu items for Sitecore members

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#443]
Context menu for Sitecore members (e.g. Identity Server, XConnect) should have the following items:

- Open Website (opens related site in a browser)
- Open web.config file

**Comment by AndreyFilchenkov** [comment]
It seems to be implemented. @DmitryKolinchuk could you please check?

**Comment by DmitryKolinchuk** [comment]
@AndreyFilchenkov, yes, I've checked this and it works in the latest SIM version.
