### ISSUE TITLE
[Import] Add support of renamed Website folder

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#45]
**Scenario:**
1. Install an instance
2. Rename Website folder to MySite
3. Update IIS to point to MySite folder
4. Export the instance
5. Delete the instance
6. Import the instance

**Actual Result:**
Error message is shown: 

```
Wrong package for import
```

**Expected Result:**
The instance is imported.

**Comment by DmitryKolinchuk** [comment]
Closed since the functionality is deprecated (disabled) for Sitecore 9 and later instances.
