### ISSUE TITLE
Test remote sql

### ISSUE THREAD

**Issue by IvanSheyenko** [Sitecore/Sitecore-Instance-Manager#452]
readme in git contains a statement that sim works only for local sql. This seems odd and should not be the case for at least for new 9 installation.

**Comment by DmitryKolinchuk** [comment]
This has been tested using [SIM 1.17.0](https://github.com/Sitecore/Sitecore-Instance-Manager/releases/tag/release%2F1.17.0) in the following way:
1. Deploy [Azure SQL Database server](https://learn.microsoft.com/en-us/azure/azure-sql/azure-sql-iaas-vs-paas-what-is-overview?view=azuresql#azure-sql-database).
2. Update MS SQL connection string as follows:
![image](https://github.com/Sitecore/Sitecore-Instance-Manager/assets/20965100/2385113d-4acc-4bb7-a28f-503116974d91)
Example of the Azure SQL Database connection string can be found [here](https://learn.microsoft.com/en-us/previous-versions/aspnet/jj653752(v=vs.110)?redirectedfrom=MSDN#windows-azure-sql-database-formerly-sql-azure-connection-string-example).

3. Install Sitecore 10.3.0 XM1.

**Result:** Sitecore and database are successfully installed.
**Notes:** Uninstall also works.
