### ISSUE TITLE
Reinstall 9.3 xm1 fails

### ISSUE THREAD

**Issue by AndreyFilchenkov** [Sitecore/Sitecore-Instance-Manager#455]
**Scenario:**  
1. Install Sitecore 9.3 xm1;
2. Reinstall it;
3. Check connection strings the CD server;

**Results**
- after step # 1 login/pass in 'security' and 'web' connection strings  are correct;
- after step # 3 login/pass in 'security' and 'web' connection strings  are wrong(and are different from the connection strings of CM instance).

**Comment by IvanSheyenko** [comment]
@AndreyFilchenkov  fixed
