### ISSUE TITLE
Re-work the list of Sitecore versions for which "Create Core Patch" utility should be visible

### ISSUE THREAD

**Issue by sc-AndriyShcherbak** [Sitecore/Sitecore-Instance-Manager#462]
For now, the ```Core Patch Creator``` is visible for Sitecore 9.0.2 and older.
- the button should be renamed from ```Create Core Patch``` to ```Create Hotfix```
- the button should be visible for Sitecore 9.1.0 and next ones;

**Comment by AndreyFilchenkov** [comment]
The task must be implemented after completing PR: https://github.com/Sitecore/Sitecore-Instance-Manager/pull/469
