### ISSUE TITLE
Remove SSPG from Bundled Tools

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#466]
The following SSPG application that is ran from SIM Bundled Tools is outdated:
[http://dl.sitecore.net/updater/sspg/SSPG.application](http://dl.sitecore.net/updater/sspg/SSPG.application)
The latest version of SSPG can be used on the admin page of Sitecore XP.

**Comment by AndreyFilchenkov** [comment]
It was decided to leave the SSPG as is for compatibility with legacy SC versions.
