### ISSUE TITLE
Create Sitecore license file converter to Base64String

### ISSUE THREAD

**Issue by AndreyFilchenkov** [Sitecore/Sitecore-Instance-Manager#472]
Example of Powershell scripts can be found on the doc Site: https://containers.doc.sitecore.com/docs/run-sitecore#preparation

Expected output: string representation of the license that will be used as a value of the environment variable in the [.env](https://containers.doc.sitecore.com/docs/run-sitecore#preparation) file.

**Comment by IvanSheyenko** [comment]
done
