### ISSUE TITLE
[Export] [Feature-Request] Customize Export

### ISSUE THREAD

**Issue by Brad-Christie** [Sitecore/Sitecore-Instance-Manager#48]
Out of necessity, kind of a multi-part ask:

1. Ability to specify [temp] location used to compile archive for export (Seems to use `%SystemDrive%\{guid}` (or maybe even specifically `C:\{guid}`)), but not helpful when you're exporting due to lack of room.
2. Ability to specify default location and naming convention of export (Each export requires a manual specification--maybe default to `{instanceName}.zip` and a default location (and re-use last supplied?)
3. Ability to mark instance for deletion after export (again, ties in with archiving to free disk space) Currently, after an export, you're left deleting the instance in a second step.

---

Looks like a minor tweak to `ExportArgs::GetTempFolder, SIM.Pipelines` takes care of 1. 3 can be solved by going further up the chain to `FileSystem.DirectoryProvider::GetTempFolder, SIM.Base` (and making it an AdvancedSetting.

_Notes to myself for when I have time, unless Alen knows a better way_

**Comment by YggY** [comment]
I believe #1 was already implemented after a request by me...see advanced setting Core/Export/TempFolder/Location

**Comment by AlenPelin** [comment]
Yes, already implemented. Closing...
