### ISSUE TITLE
ERROR: You don't have any standalone product package in your repository

### ISSUE THREAD

**Issue by chiragp** [Sitecore/Sitecore-Instance-Manager#51]
Have error installing Sitecore instances on SIM 1.4 Update 2.  I have set my repository to my secondary hard drive (D:) but even after moving it to primary drive (C:) still have the error.  With SIM 1.4 Update 1, everything works as long as I have the tool on the same drive as my repository. I'm running Windows 10.

[2015-12-25_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/72273/2015-12-25_DEBUG.txt)
[2015-12-25.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/72272/2015-12-25.txt)

**Comment by AlenPelin** [comment]
Try removing %APPDATA%\Sitecore\Sitecore Instance Manager\Cache folder and restarting SIM.

**Comment by AlenPelin** [comment]
Should be fixed in the latest QA build http://dl.sitecore.net/updater/qa/sim
