### ISSUE TITLE
Update-8.1x not recognizing existing Repos!

### ISSUE THREAD

**Issue by gunasekaransengodan** [Sitecore/Sitecore-Instance-Manager#53]
Trying to install Update-8.1x from existing repo (that previously worked) n't recognized by SIM and when i try to download them via version down loader not able to download 8.1x. 

[Error Image Click Here](https://cloud.githubusercontent.com/assets/12053710/12050889/4081462c-af21-11e5-9010-41b7e6cbe264.png)

I'm using SIM 1.4 rev. 150618
I'm not even able to use SIM 'Get Sitecore' option to get directly from cloud instead local repo.
Download works only up to 8.0x not for 8.1x

**Comment by AlenPelin** [comment]
The issue is fixed by https://github.com/Sitecore/Sitecore-Instance-Manager/commit/bd976b5731d5dab165c4a906bf77f59321a25807

Please check latest QA build http://dl.sitecore.net/updater/qa/sim

**Comment by gunasekaransengodan** [comment]
Yes Fixed Alen. thank you.
