### ISSUE TITLE
No explanation of what to do when "Get Sitecore" fails

### ISSUE THREAD

**Issue by arencambre** [Sitecore/Sitecore-Instance-Manager#552]
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!! READ THIS CAREFULLY !!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!                                                     !!
!! 1. Do not remove any sections from this template    !!
!! 2. Do not create issue without SIM version AND logs !!
!! 3. Remove this disclaimer before posting issue      !!
!!                                                     !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Description:**  
When I am going through the wizard initiated by the **Get Sitecore** button, I get an error after entering my username and password. If I look in the log files, it shows as a 500 error.

If there is a reason why I cannot log in anymore, that is fine, but please provide workaround instructions. Without a workaround, as long as this critical feature is broken, SPIF has no use because no products show (empty **Product** dropdown):
![image](https://user-images.githubusercontent.com/411495/106815928-35b32000-663a-11eb-80fd-f11a8e8b650f.png)

**Scenario:**  
1.  Attempt to download Sitecore 9.0.2 using the **Get Sitecore** feature.

**Issue is actual**  
I hereby confirm the issue is new:
* it was not discussed before (I used GitHub Issues search)

**Valid for QA/DEV**  
I hereby confirm the issue is reproducible on the latest QA/DEV version [1.8.0.710]

**Screenshots:**
Please find screenshots 
![image](https://user-images.githubusercontent.com/411495/106815722-dead4b00-6639-11eb-83ae-07b052243927.png)

**Attachments:**  
Logs:
[2021-02-03.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/5921827/2021-02-03.txt)
[2021-02-03_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/5921828/2021-02-03_DEBUG.txt)

**Comment by arencambre** [comment]
At least for 9.0.2, it looks like downloading the copy in the **Packages for XP Single** link from https://dev.sitecore.net/Downloads/Sitecore_Experience_Platform/90/Sitecore_Experience_Platform_90_Initial_Release.aspx, then putting it in SIM's repository folder, is sufficient. I am unclear where this is documented.

**Comment by DmitryKolinchuk** [comment]
The described scenario is not reproduced in the latest SIM version, because the obsolete login functionality to download packages from [dev.sitecore.net](https://dev.sitecore.net/) was removed since they are now publicly available.
The related issue and PR can be found below:
[https://github.com/Sitecore/Sitecore-Instance-Manager/issues/177](https://github.com/Sitecore/Sitecore-Instance-Manager/issues/177)
[https://github.com/Sitecore/Sitecore-Instance-Manager/pull/588](https://github.com/Sitecore/Sitecore-Instance-Manager/pull/588)
