### ISSUE TITLE
SIM depends on ProxyDisabler to install packages. That does not exist in Sitecore 9.

### ISSUE THREAD

**Issue by arencambre** [Sitecore/Sitecore-Instance-Manager#553]
I am running SIM 1.5 because 1.8 is very buggy.

Note this reference to ProxyDisabler: https://github.com/Sitecore/Sitecore-Instance-Manager/blob/618ddea6e723fdbbd8ed59dd3d8815bd4f26075e/src/SIM.Pipelines/Agent/AgentFiles.cs#L48

This causes an error when **/sitecore/shell/sim-agent/InstallPackage.aspx** is run. The error happens because there is no ProxyDisabler in Sitecore 9. This is affirmed here: https://briancaos.wordpress.com/2018/01/22/in-sitecore-9-the-proxydisabler-have-been-retired-completely/.

**Comment by IvanSheyenko** [comment]
@arencambre 
Hi Aren. SIM 1.8 does not support packages installation for 9+ (we will add this in future versions). UI does not provide such an option. Could you please provide details on how you encounter the error?
