### ISSUE TITLE
Some Sitecore 9.0.x sites have non-SSL binding after installation

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#579]
While fixing the issue mentioned in the following PR I noticed that the Sitecore site of 9.0.2 XP0 topology has non-SSL binding:
[https://github.com/Sitecore/Sitecore-Instance-Manager/pull/570](https://github.com/Sitecore/Sitecore-Instance-Manager/pull/570)
However, the XConnect site has the SSL binding.
In **9.0.2 XP1**, the **CD** site doesn't have SSL binding and the **CM, DDS, Processing, Reporting** sites have SSL bindings.
In **9.0.2 XM1**, the **CD** site doesn't have SSL binding and the **CM** site has SSL binding.
Looks like this is by design and controlled by the default Sitecore PowerShell scripts that are used for installation.
However, is it possible to change this behavior on the SIM side in order to have SSL bindings for all Sitecore sites after installation?

**Comment by AndreyFilchenkov** [comment]
The behavior is defined by the SIF scripts. So it is by design.
