### ISSUE TITLE
Outdated link to 'WebPlatformDownload' installer in 'Prerequisites.json' file

### ISSUE THREAD

**Issue by AndreyFilchenkov** [Sitecore/Sitecore-Instance-Manager#595]
**Description:**
To install Sitecore 9+, SIM uses SIF under the hood.

Since the WDP packages for On-Premises deployment contain outdated links to the 'Microsoft Web Platform Installer 5.0' in the Prerequisites.json file, the installation of Sitecore may fail in case the Prerequisites task is checked to be run.

It may cause failure during the installation process. 
```
...
[-------- DownloadWebPlatformInstaller : DownloadFile ------------------------]
[DownloadWebPlatformInstaller]:[Download] 
https://download.microsoft.com/download/C/F/F/CFF3A0B8-99D4-41A2-AE1A-496C08BEB904/WebPlatformInstaller_amd64_en-US.msi 
=> C:\Users\{user}\AppData\Local\Temp\WebPlatformInstaller_amd64_en-US.msi
Install-SitecoreConfiguration : Error downloading https://download.microsoft.com/download/C/F/F/CFF3A0B8-99D4-41A2-AE1A-
496C08BEB904/WebPlatformInstaller_amd64_en-US.msi: The remote server returned an error: (404) Not Found.
At line:24 char:1
+ Install-SitecoreConfiguration @installParams *>&1 | Tee-Object Prereq ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Install-SitecoreConfiguration
...
```

**We need to:** create a known issue article on the WIKI to describe how to overcome the issue.

**Comment by DmitryKolinchuk** [comment]
The known issue has been added to WIKI:
[https://github.com/Sitecore/Sitecore-Instance-Manager/wiki/Known-Issue-Outdated-Download-Link-to-Microsoft-Web-Platform-Installer](https://github.com/Sitecore/Sitecore-Instance-Manager/wiki/Known-Issue-Outdated-Download-Link-to-Microsoft-Web-Platform-Installer)
