### ISSUE TITLE
ConfigBuilderButton does not work for Sitecore 10+

### ISSUE THREAD

**Issue by DmitryKolinchuk** [Sitecore/Sitecore-Instance-Manager#617]
**Scenario:**  
1. Open SIM DEV 1.11.0.932.
2. Select any Sitecore 10+ instance (not member).
3. Use any ".xml" command under the "Config Files" menu (e.g. ShowConfig.xml):
![image](https://user-images.githubusercontent.com/20965100/134507828-d525accf-b7a3-4644-8a7f-9ae64eb8a761.png)

**Result:** the following error occurs:
_Error during handling menu button click: SIM.Tool.Windows.MainWindowComponents.Buttons.ConfigBuilderButton
System.InvalidOperationException: Failed to get web config result of C:\inetpub\wwwroot\sc1001xp0\sc1001xp0.local ---> System.InvalidOperationException: Failed to build configuration. Reason: An error occurred loading a configuration file: Could not load type 'Sitecore.Configuration.FlexibleEnvironmentConfigBuilder' from assembly 'Sitecore.Kernel'. (C:\inetpub\wwwroot\sc1001xp0\sc1001xp0.local\web.config line 21)_
![image](https://user-images.githubusercontent.com/20965100/134508251-d8ed09b4-f05b-4ae7-be94-dae8e8c53270.png)

May be related to the outdated [Config Builder](https://dev.azure.com/Sitecore-PSS/Sitecore%20Config%20Builder) version that is used in SIM.

**Comment by DmitryKolinchuk** [comment]
The issue is not reproduced using the develop branch (latest commit 82e4a32cd1db206aa3fed4e878c257f7f5faf0cf [82e4a32]).

**Comment by AndreyFilchenkov** [comment]
The issue was fixed by referencing the new version of the Diagnostics Libraries in commit: 391e6486d9664c9b76740ec1cc2a84d04b9bac04
