### ISSUE TITLE
'Esc' key closes all dialogs

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#62]
**Steps to reproduce:**
1. Open 'Install instance' wizard.
2. Proceed to 'Custom Packages' step.
3. Click 'Add package' button.
4. Hit 'Esc' to close 'Choose Package' dialog.

**Actual result:**

All windows are closed, even 'Install instance'.

**Expected result:**

Only 'Choose Package' dialog is closed, and 'Install Instance' is still open.

**Comment by DmitryKolinchuk** [comment]
Closed since the functionality related to installation of Sitecore 8 and earlier versions is outdated.
