### ISSUE TITLE
Packages that were downloaded by SIM are not supported for installation in SIM

### ISSUE THREAD

**Issue by sc-AndriyShcherbak** [Sitecore/Sitecore-Instance-Manager#622]
**Description:**  
Packages that were downloaded by SIM are not supported for installation in SIM

**Scenario:**  
1.  Open "Bundled Tools"
2. Click "Download Sitecore"
3. Choose e.g. Sitecore 9.1.1 and download it.
4. Click "Install on-prem" and choose the downloaded version and package

**Actual Result:** "The selected installation package is not supported. Please choose a package for "On Premises" deployment." message box appears
**Expected Result:**  No issues with this installation

**Screencast:** [https://www.screencast.com/t/cRRpaDoXXY](url)

**Logs:**  [https://sitecore.box.com/s/lg2d47wb6pe4qzhld1tvyg757r17i38b](url)

**Comment by DmitryKolinchuk** [comment]
The "Download8Button" class is responsible for the "Download Sitecore" command and it was designed to download only Sitecore 8 and earlier versions.
To be able to downlead Sitecore 9+ versions new functionality should be introduced.
As we discussed with @AndreyFilchenkov, in scope of this issue, the additional check should be added if a user tries to download Sitecore 9+ version and display a warning that starting from Sitecore 9+ artifacts have been changed, so a package should be downloaded manually from the following site:
[https://dev.sitecore.net/Downloads/Sitecore_Experience_Platform.aspx](https://dev.sitecore.net/Downloads/Sitecore_Experience_Platform.aspx)
