### ISSUE TITLE
When "Right click -> Browse Sitecore Client" on a Sitecore XP solution in SIM, sometimes Experience Editor is opened

### ISSUE THREAD

**Issue by SC-IDO** [Sitecore/Sitecore-Instance-Manager#627]
**Description:**  
When "Right click -> Browse Sitecore Client" on a Sitecore XP solution in SIM, sometimes Experience Editor is opened.

**Scenario:**  
1.  Using SIM, "Right click -> Browse Sitecore Client" on a Sitecore XP solution

**Issue is actual**  
Instead of Sitecore Shell (Desktop/Launchpad), sometimes Experience Editor is opened. It takes some time to wait until it is loaded completely to be able to switch to Desktop/Launchpad, especially when a heavy module like SXA is installed.
Consider changing the opened Sitecore Client URL from "/sitecore" to "/sitecore/shell" to fix this EE opening, or make this URL configurable, f.e. in Advanced Settings.

**Valid for QA/DEV**  
Haven't checked in QA/DEV versions, I observe this behavior in several latest versions of SIM. Frankly speaking, I suspect that behavior of Google Chrome has changed so the issue has appeared. Suddenly the issue has appeared with all Sitecore XP versions and I don't remember any SIM updates at that moment.

**Screenshots:**
-

**Attachments:**  
-

**Comment by DmitryKolinchuk** [comment]
We already have the following button definition that leads to "/sitecore/shell":
```
new ButtonDefinition
{
  Label = "Sitecore Desktop",
  Image = "/Images/$sm/Windows Table.png, SIM.Tool.Windows",
  Handler = new BrowseButton("/sitecore/shell")
},
```
According to the discussion with @AndreyFilchenkov and @SC-IDO, it was decided to add this button to the context menu, so now a user have a possibility to chose between Browse Sitecore Client ("/sitecore") and Browse Sitecore Desktop ("/sitecore/shell"):
![image](https://user-images.githubusercontent.com/20965100/150140058-4e115901-df2b-40a9-a3ee-0721cd00c97d.png)
