### ISSUE TITLE
Changes to Integrated Security in the Connection String settings not persisting.

### ISSUE THREAD

**Issue by NasC0** [Sitecore/Sitecore-Instance-Manager#63]
SIM does not persist changes to the connection string settings. Tried setting True or SSPI, installed instance always has False setup.
Connection string (currently set) format (Data Source blanked out): 

Data Source=*************\***********;Integrated Security=SSPI

Thanks.

**Comment by AlenPelin** [comment]
It is a known issue, it is not supported:
https://github.com/Sitecore/Sitecore-Instance-Manager/wiki/Troubleshooting 

And actually it is by design - SIM is a development/testing tool which assumes you have default User Id=sa; Password=12345 credentials everywhere.

**Comment by AlenPelin** [comment]
BTW. There is a pull request that fixes the issue:
https://github.com/Sitecore/Sitecore-Instance-Manager/pull/58
