### ISSUE TITLE
Can't generate NUGET packages from SIM

### ISSUE THREAD

**Issue by BlazinSkillz** [Sitecore/Sitecore-Instance-Manager#64]
Here's the error:

System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks, Version=2.6.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Threading.Tasks, Version=2.6.8.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Threading.Tasks, Version=1.5.11.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Running under executable  C:\Users\larry.allen\AppData\Local\Apps\2.0\AMN3LOH0.KOA\OBGN1CH2.E7Y\sim...tion_abafaebf7cc9a2b2_0001.0004_5fb5cf1ab2ace396\SIM.Tool.exe

**Comment by AlenPelin** [comment]
@BlazinSkillz what SIM version? what OS version?

**Comment by BlazinSkillz** [comment]
Thanks for the reply. It's SIM 1.4.0.227 on Windows 10 enterprise.

**Comment by AlenPelin** [comment]
@BlazinSkillz Already fixed in qa version.
http://dl.sitecore.net/updater/qa/sim
