### ISSUE TITLE
The help page for changing the default SQL Server account is a 404

### ISSUE THREAD

**Issue by jermdavis** [Sitecore/Sitecore-Instance-Manager#67]
I attempted to install SIM 1.4.0.227 via http://dl.sitecore.net/updater/sim/ earlier. 
The installer got to the "network service" page:
![wizardpage](https://cloud.githubusercontent.com/assets/7868341/12875021/c2b27cb2-cdd8-11e5-95c9-049a2df53a54.png)
Since the machine was using MSSQLServer account to run SQL Server, clicking next threw up a warning message:
![errormsg](https://cloud.githubusercontent.com/assets/7868341/12875031/032852a8-cdd9-11e5-8c7c-0ec3ebc256a6.png)
But when I clicked the "ok" button to read the further help, I got a 404 for the page https://bitbucket.org/alienlab/sitecore-instance-manager/wiki/KnownIssue-SqlServerDefaultAccount
![browser404](https://cloud.githubusercontent.com/assets/7868341/12875044/53cf2920-cdd9-11e5-88e0-4e603f480cbb.png)
I guess the link in the code needs updating in [src/SIM.Tool.Windows/UserControls/Setup/Permissions.xaml.cs](https://github.com/Sitecore/Sitecore-Instance-Manager/search?utf8=%E2%9C%93&q=KnownIssue-SqlServerDefaultAccount)?
I tried a brief google for a new url but didn't find one - otherwise I would have put in a PR...

**Comment by AlenPelin** [comment]
You need this page:
https://github.com/Sitecore/Sitecore-Instance-Manager/wiki/Troubleshooting

**Comment by KamiShikkaku** [comment]
The troubleshooting page only has dead links. Where can I find out what to do when I experience this error?

**Comment by AlenPelin** [comment]
@KamiShikkaku thanks for pointing out, the dead links are now fixed.
