### ISSUE TITLE
Cannot connect to IIS even if service is running.

### ISSUE THREAD

**Issue by alex-bergeron** [Sitecore/Sitecore-Instance-Manager#69]
I'v had this bug on three different workstations. I get: Cannot connect to IIS. Make sure it is installed and running. W3SVC is running perfectly fine and my IIS (7.5, std setup) is working perfectly fine. I tried making a .bat to lunch the ClickOnce and then run this batch file with admin access with no luck.

Screenshot (my win7 is in french): ![sim_tool_error_ss](https://cloud.githubusercontent.com/assets/6451810/13638179/1f13de20-e5d9-11e5-9164-008481de375c.PNG)

Here is the log file content (the line in french: "Le service spécifié n’existe pas en tant que service installé" translates to: "The specified service doesn't exists as an installed service", just in case. ): 

`   1 16:37:24,517 INFO  **********************************************************************
   1 16:37:24,522 INFO  **********************************************************************
   1 16:37:24,522 INFO  Sitecore Instance Manager started
   1 16:37:24,522 INFO  Version: 1.4.0.227
   1 16:37:24,522 INFO  Revision: rev.160229-623
   1 16:37:24,522 INFO  Label: ClickOnce
   1 16:37:24,522 INFO  Executable: C:\Users\alex.bergeron\AppData\Local\Apps\2.0\JXNOT4V9.QPE\NEHATJ3M.82W\sim...tion_abafaebf7cc9a2b2_0001.0004_5fb5cf1ab2ace396\SIM.Tool.exe
   1 16:37:24,522 INFO  Arguments: <NO ARGUMENTS>
   1 16:37:24,522 INFO  Directory: C:\Users\alex.bergeron\AppData\Local\Apps\2.0\JXNOT4V9.QPE\NEHATJ3M.82W\sim...tion_abafaebf7cc9a2b2_0001.0004_5fb5cf1ab2ace396
   1 16:37:24,523 INFO  **********************************************************************
   1 16:37:24,523 INFO  **********************************************************************
   1 16:37:24,526 INFO  Error during checking IIS state
System.InvalidOperationException: Service World Wide Web Publishing Service was not found on computer '.'. ---> System.ComponentModel.Win32Exception: Le service spécifié n’existe pas en tant que service installé
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.GenerateNames()
   at System.ServiceProcess.ServiceController.get_DisplayName()
   at SIM.Tool.App.CheckIIS()
`

**Comment by AlenPelin** [comment]
Already fixed in QA

**Comment by AlenPelin** [comment]
http://dl.sitecore.net/updater/sim

**Comment by alex-bergeron** [comment]
Oh and I didn't even tried QA, awesome thanks a lot!

**Comment by mathieu-benoit** [comment]
Thanks @AlenPelin and @alex-bergeron, I had the same issue and the QA version fixed it.
