### ISSUE TITLE
The value of "Project name" is ignored when "Include topology and tag to the project name" is unchecked

### ISSUE THREAD

**Issue by AndreyFilchenkov** [Sitecore/Sitecore-Instance-Manager#698]
**Description:**
The issue is: The value of ```Project name``` is ignored when ```Include topology and tag to the project name``` is unchecked

**Scenario:**  
1. Click "Deploy to Docker" button
2. Fill in the "Project name" field with some unique value (e.g. test-proj-name)
3. Click "Next" button
4.  Set topology to "XP0", and select proper tag
5. Uncheck the "Include topology and tag to the project name" checkbox
6. Click next and install deploy the environment.

**Actual Result:**
The default value('sitecore-xp0') is used as project name instead of gfived in step#2(test-proj-name).
The proj name can be found in the 
- ```hosts``` file
- ```Environments.json``` file

**Valid for QA/DEV**  
I hereby confirm the issue is reproducible on the latest QA/DEV version: rc/1.15

**Comment by DmitryKolinchuk** [comment]
I also noticed that host names are not updated in the following method:
```
private void ProjectName_OnUnchecked(object sender, RoutedEventArgs e)
{
  this.envModel.ProjectName = this.defaultProjectName;
}
```
The following method call should be used:
`this.UpdateHosts();`
