### ISSUE TITLE
SIM breaks hosts file 

### ISSUE THREAD

**Issue by dufkaf** [Sitecore/Sitecore-Instance-Manager#70]
The format of C:\Windows\System32\drivers\etc\hosts allows multiple host names for same IP line like:
127.0.0.1 name1 name2 name3 name4 name5 ....
After trying SIM and letting it create and remove sitecore instance I noticed I could not use my local websites defined like above and when checking the hosts file I see the file is completely reformatted and all my additional names are gone! Also the file allows comments starting with '#' and they appears to be gone too!

When checking the src/SIM.Adapters/WebServer/Hosts.cs  code it explains a lot :-)

Please keep the original file as is including comments when modifying it. You can add/remove your own lines (you can even mark them with special # comment lines for better handling) but do not touch the rest!

**Comment by AlenPelin** [comment]
Thanks @dufkaf for an issue report and for letting me know of hosts file magic :) but it would be difficult to fix the issue according to your preferences - SIM does what it does because it is the simplest way. You are the first person who complained about that since it was created 5 years ago. So I assume that nobody else cares of the format in their hosts file. You are welcome to fork the repo, fix the issue and send a pull request. Or use a workaround - use hosts as comments and single host per line.

**Comment by dufkaf** [comment]
OK, no problem. I just tried SIM and reported a bug. The file format is documented in many places including Wikipedia and current SIM code does not handle it correctly. You are definitely free to ignore it.

As for the "simplest way" I would guess  treating the file as random text and adding/removing single line (possibly with some marker in comments if it is needed for internal SCIM identification) like
127.0.0.1 xx #SCIM instance xx
would be the simplest way to do it and far more robust that trying to parse the file but I guess I don't understand enough of the code to see advantages/necessity or parsing it completely. If getting all entries is needed for some reason other than regenerating it (?) then the parsing code makes sense but still I wouldn't call saving it by regenerating it from scratch to be 'the simplest way' even if it would not break stuff like it currently does.

In fact when looking at the src/SIM.Adapters/WebServer/Hosts.cs file the phrase "simplest way" is one that didn't come to my mind at all when trying to understand the code ;-)

But still thank you for SIM, it is great it is there including source :-)

**Comment by AlenPelin** [comment]
Thanks for your input here. I will take your opinion into consideration when writing next major version of SIM someday.
