### ISSUE TITLE
Error when trying to install sim tool from http://dl.sitecore.net/updater/sim

### ISSUE THREAD

**Issue by reyrahadian** [Sitecore/Sitecore-Instance-Manager#72]
Below is the error that I got (complete error is attached
[5HEDHLQY.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/227762/5HEDHLQY.txt)

)

PLATFORM VERSION INFO
	Windows 			: 6.2.9200.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1055.0 built by: NETFXREL2
	clr.dll 			: 4.6.1055.0 built by: NETFXREL2
	dfdll.dll 			: 4.6.1055.0 built by: NETFXREL2
	dfshim.dll 			: 6.3.9600.16384 (winblue_rtm.130821-1623)

SOURCES
	Deployment url			: file:///C:/Users/rera/Downloads/SIM.Tool.application
	Deployment Provider url		: http://dl.sitecore.net/updater/sim/SIM.Tool.application
						Server		: Microsoft-IIS/7.5
						X-Powered-By	: ASP.NET
	Application url			: http://dl.sitecore.net/updater/sim/Application%20Files/SIM.Tool_1_4_0_227/SIM.Tool.exe.manifest
						Server		: Microsoft-IIS/7.5
						X-Powered-By	: ASP.NET

IDENTITIES
	Deployment Identity		: SIM.Tool.application, Version=1.4.0.227, Culture=neutral, PublicKeyToken=abafaebf7cc9a2b2, processorArchitecture=x86
	Application Identity		: SIM.Tool.exe, Version=1.4.0.227, Culture=neutral, PublicKeyToken=abafaebf7cc9a2b2, processorArchitecture=x86, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\Users\rera\Downloads\SIM.Tool.application resulted in exception. Following failure messages were detected:
		+ The requested operation requires elevation. (Exception from HRESULT: 0x800702E4)

**Comment by AlenPelin** [comment]
@reyrahadian please make sure that your current user is administrator

**Comment by reyrahadian** [comment]
Using SIM QA Version seems to work instead
