### ISSUE TITLE
Allow Local Respository to live in a network share

### ISSUE THREAD

**Issue by rauljmz** [Sitecore/Sitecore-Instance-Manager#73]
Trying to set the local repository in a network share, or in a network mapped drive letter gives an error as it thinks the directory does not exist.
Also in the browse folder dialog it is no possible to access network locations.

**Comment by AlenPelin** [comment]
This is by design. Use https://github.com/Sitecore/Sitecore-Instance-Manager/wiki/Advanced#appdownloaderexternalrepository
