### ISSUE TITLE
Install bug in TestSqlServer

### ISSUE THREAD

**Issue by nbenninghoff** [Sitecore/Sitecore-Instance-Manager#77]
public virtual bool TestSqlServer(string rootPath, string connectionString)

if rootPath does not exist on the machine specified in connectionString, installation fails with misleading error:
"You probably don't have necessary permissions set. Please try to click 'Grant' button before you proceed."

**Comment by AlenPelin** [comment]
Using remote SQL Server is not supported by SIM. In the case of local SQL Server, presence of this folder is checked in the previous step.
