### ISSUE TITLE
App/Tools/VisualStudio/Version option isn't valid anymore

### ISSUE THREAD

**Issue by KayeeNL** [Sitecore/Sitecore-Instance-Manager#79]
Hi @AlenPelin 

The following option mentioned on https://github.com/sitecore/sitecore-instance-manager/wiki/Advanced isn't a valid option anymore.

App/Tools/VisualStudio/Version

The version of Visual Studio to display correct project templates in the Custom Packages step.

Default value: 2012

Robbert

**Comment by AlenPelin** [comment]
Thanks. Removed from wiki.
