### ISSUE TITLE
Use SIM to configure Sitecore specific Role(s) - feature request

### ISSUE THREAD

**Issue by reyrahadian** [Sitecore/Sitecore-Instance-Manager#88]
Would it be possible to create an extension with SIM to configure Sitecore to specific role(s) ?

I imagine on the SIM website list window, there's an additional button to configure the selected website as a CM/CD/Processing role

Is this something that you've look into doing as well? or is it hard to achieve due specific Sitecore role configurations steps, eg: 8.0 vs 8.1

**Comment by AlenPelin** [comment]
It is already implemented as CD for 8.1 (Install / Install Modules -> Configuration Presets -> Configuration - Sitecore 8.1 - Scaling - CD.zip). You are welcome to do the same for other roles in your fork - pull request is appreciated. 

However we have some internal codebase for similar purpose and we are evaluating if we can just integrate already existing code with SIM so please consider this before investing valuable amount of time in it. 

And I still have plans for SIM 2 which supports that native as a part of solutions (not separate instances like now).

**Comment by AlenPelin** [comment]
For your reference:
* [Configuration - Sitecore 8.1 - Scaling - CD.zip](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/518a9febc94100172d72d5b1f4f951c9b920ceb0/src/SIM.Tool/Configurations/Configuration%20-%20Sitecore%208.1%20-%20Scaling%20-%20CD.zip) - empty zip as a placeholder for manifest
* [Configuration - Sitecore 8.1 - Scaling - CD.manifest.xml](https://github.com/Sitecore/Sitecore-Instance-Manager/blob/518a9febc94100172d72d5b1f4f951c9b920ceb0/src/SIM.Tool/Configurations/Configuration%20-%20Sitecore%208.1%20-%20Scaling%20-%20CD.manifest.xml)

**Comment by reyrahadian** [comment]
Thanks Alen!. 

I'll have a look later on to see how the CD configuration for 8.1 is done in SIM

**Comment by AlenPelin** [comment]
Implemented by #160
