### ISSUE TITLE
Add support of ASP.NET precompilation

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#9]
In order to increase Sitecore 8 startup performance we need to implement a configuration package that will perform ASP.NET precompilation during the installation stage. Note that this process takes about 5 minutes on relatively fast laptop with 2 cores, 16GB RAM and 512GB SSD.

**Comment by Brad-Christie** [comment]
To my knowledge this is going to be tricky; I had a customer approach me about doing this and ran into trouble (support ticket #439860). Also, just tried the same on a clean install of sc81rtt and ran into a similar problem (we're still referencing controls from older versions of the framework):

> /sitecore/admin/Wizard/InstallationLog.ascx(1): error ASPPARSE: The base class includes the field 'logPanel', but its type (System.Web.UI.HtmlControls.HtmlGenericControl) is not compatible with the type of control (System.Web.UI.HtmlControls.HtmlIframe).

**Comment by AlenPelin** [comment]
@Brad-Christie thanks for your feedback. I had seen and reported the error you mentioned a while ago, but it can be easily worked around by ignoring (don't remember how exactly) that folder entirely. 

This wish was posted by our dev team that recommends this approach. In my personal opinion it doesn't matter if these files are precompiled by SIM or by Sitecore itself as it will take similar time and happens only once.

**Comment by DmitryKolinchuk** [comment]
Closed since the functionality related to installation of Sitecore 8 and earlier versions is outdated.
