### ISSUE TITLE
Skip database actions mode

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#90]
Implement an advanced setting that will skip all database-related actions. This may be required when using SIM out of developer's machine.

**Comment by KayeeNL** [comment]
And have windows authentication enabled in the connectionstrings.config @AlenPelin , so no username and password

**Comment by AlenPelin** [comment]
Windows Authentication is not supported.

**Comment by AlenPelin** [comment]
Fixed by b3ff4ad00a36f5df20a31aa65cf0eab1ac216189
