### ISSUE TITLE
Exporting a site hangs when Sitecore ECommerce Services is installed

### ISSUE THREAD

**Issue by nicolas-stephens** [Sitecore/Sitecore-Instance-Manager#93]
**Importance:**  
- **Critical** (I need this issue to be fixed)  

**Description:**  
I'm trying to export a local Active Commerce site for use by other developers. The site is running Sitecore 8.1.3, which was installed via SIM, Sitecore E-Commerce Services 2.2, Sitecore E-Commerce Order Manager 2.2, and Active Commerce 3.3.0. 

The Sitecore E-Commerce packages insert two mdf and ldf files into the App_Data directory of the site. SitecoreEcommerce_ActionLog.ldf/mdf and SitecoreEcommerce_Orders.ldf/mdf. During the export process, having checked all boxes except for "Remove License File", the export process hangs on "Assembling zip package". There are no errors in the logs, but the process just sits there with the action state of "Running".

Based on a previous bug reported about ldf files, I ended up removing the ldf files from the App_Data directory, but that didn't fix it. I then proceeded to remove the entire contents of the App_Data directory, all four files. Running the export again, with the same configuration settings, the export completes successfully.

The log attached has a final error which the thread abort from when I click cancel on the exporting instance window.

**Scenario:**  
1. Install 8.1.3
2. Install Sitecore E-Commerce Services 2.2
3. Install Sitecore E-Commerce Order Manager 2.2
4. Export site including all databases and deleting all options except the license file

**Attachments:**  
Please find attached latest log files from this folder:  
[2016-06-30.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/341691/2016-06-30.txt)
[2016-06-30_DEBUG.txt](https://github.com/Sitecore/Sitecore-Instance-Manager/files/341690/2016-06-30_DEBUG.txt)

```
%APPDATA%\Sitecore\Sitecore Instance Management\logs 
```

**Comment by DmitryKolinchuk** [comment]
Closed since the functionality is deprecated.
