### ISSUE TITLE
SIM is not available offline

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/Sitecore-Instance-Manager#99]
**Importance:**
**Critical** (I need this issue to be fixed)  

**Description:**
SIM is not available offline

**Scenario:**
1. Disable network connection
2. Try to run SIM

**Comment by AlenPelin** [comment]
Postponed.

**Comment by jflheureux** [comment]
For people who want to run SIM offline in the meantime, I wrote an article for a workaround: https://www.jflh.ca/2016-07-22-run-sitecore-sim-tool-offline

**Comment by DmitryKolinchuk** [comment]
The issue is not reproduced using [SIM 1.17.0](https://github.com/Sitecore/Sitecore-Instance-Manager/releases/tag/release%2F1.17.0).
